--[[--------------------------------------------------
003_Alliance_20to30.lua
Authors: mrmr
Version: 1.04.2
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 20 to Lvl 30
    1.04.1
        -- First Release
            Alliance's Guide
            from level 20 to lever 30
    1.04.2
        -- no changes in here for this revision
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Alliance_20to30 = {
-----------20-21 Darkshore
    --[201] = {
    [2021] = {
        title = "23-24 Wetlands",
        --n = "20-21 Darkshore",
        --pID = 104, nID = 202, 
        --itemCount = 10,
        items = {
            
{ str = "Accept #ACCEPTYoung Crocolisk Skins#", y = 55.73, x = 8.54, QA = 484, zone = "Wetlands"},
{ str = "Accept #ACCEPTClaws from the Deep#", y = 58.53, x = 8.3, QA = 279, zone = "Wetlands", unitscan = "GOBBLER"},
{ str = "Get the  Wetlands FP  ", typ = "fp"},
{ str = "Accept #ACCEPTThe Third Fleet#  \nAccept #ACCEPTThe Greenwarden#", y = 59.66, x = 10.89, QA = {288,463}, zone = "Wetlands"},
{ str = "#DOQUESTBuy a flagon of mead from the innkeeper#", y = 60.95, x = 10.7, zone = "Wetlands", QC = 288},
{ str = "Go upstairs, turn in #TURNINThe Absent Minded Prospector#, skip the follow up", y = 60.43, x = 10.84, zone = "Wetlands", QT = 942},
{ str = "Turn in #TURNINThe Third Fleet#", y = 59.66, x = 10.89, zone = "Wetlands", QT = 288},
{ str = "Look for a Bronze Tube at the npc inside the keep\nKill #DOQUESTYoung Wetlands Crocolisks#\n \nDo #DOQUESTClaws from the Deep#", y = 39.83, x = 18.06, zone = "Wetlands", QC = 279},
{ str = "Look for a Bronze Tube at the gnome npc", y = 25.76, x = 26.4, zone = "Wetlands"},
{ str = "Accept #ACCEPTDaily Delivery#", y = 39.36, x = 49.91, QA = 469, zone = "Wetlands"},
{ str = "Turn in #TURNINThe Greenwarden#\n \nAccept #ACCEPTTramping Paws#", y = 40.4, x = 56.37, QA = 276, zone = "Wetlands"},
{ str = "Do #DOQUESTTramping Paws#", y = 71.32, x = 61.91, zone = "Wetlands", QC = 276},
{ str = "Grind to level 24"},
{ str = "Turn in #TURNINTramping Paws#  \nAccept #ACCEPTFire Taboo#", y = 40.4, x = 56.37, QA = 277, zone = "Wetlands", QT = 276},
{ str = " Head to Loch Modan  \nOR \nUse the website unstuck feature and skip the rest of this segment if you already have the Loch Modan FP", y = 72.3, x = 54.5, zone = "Wetlands"},
{ str = "Accept #ACCEPTA Dark Threat Looms#", y = 13.61, x = 46.04, QA = 250, zone = "Loch Modan"},
{ str = "Click on the #TURNINSuspicious Barrel#  \nAccept #ACCEPTA Dark Threat Looms# pt.2", y = 13.23, x = 56.05, QA = 199, zone = "Loch Modan", QT = 250},
{ str = "Turn in #TURNINA Dark Threat Looms pt.2#  \nSkip the follow up", y = 13.61, x = 46.04, zone = "Loch Modan", QT = 199},
{ str = "Throw away your HS and unstuck to Thelsamar\nAccept #ACCEPTStonegear's Search#\n \n Get the  Thelsamar Flight Path", y = 50.95, x = 33.93, zone = "Loch Modan", typ = "fp"},
{ str = "From this point forward you will save about 10-15 minutes using the website unstuck to teleport to SW and skipping the rest of this segment\n \n Run to Dun Morogh", y = 68.6, x = 21.3, zone = "Loch Modan"},
{ str = "Once you get to Dun Morogh, throw away your HS and unstuck \n \nTurn in #TURNINStonegear's Search#", y = 48.61, x = 49.62, zone = "Dun Morogh", QT = 467},
{ str = " Buy a Bronze Tube if you haven't already\n \n Run to Ironforge", y = 87.1, x = 14.9, zone = "Ironforge"},
{ str = "Turn in #TURNINThe Powers Below# if you have it\nTurn in #TURNINAn Old Colleague# (optional, you can turn it in later)\nBuy a Bronze Tube if you haven't already\n \nTake the tram to Stormwind"},
        }
    },


-----------21-22 Ashenvale
    --[202] = {
    [2122] = {
        title = "24-25 Duskwood part 1",
        --n = "21-22 Ashenvale",
        --pID = 201, nID = 203, 
        --itemCount = 33,
        items = {


{ str = "Deposit the following items: \nGobbler's Head \nBundle of Crocolisk Skins \nYoung Crocolisk Skin (x4) \n Buy a Bronze Tube if you haven't\n \nHead to Stormwind City \nTurn in #TURNINA Scroll from Mauren#  \nAccept #ACCEPTDevils in Westfall#", y = 80.15, x = 42.79, QA = 1076, zone = "Stormwind City", QT = 1075},
{ str = " Head to Elwynn Forest", y = 89.1, x = 71.19, zone = "Stormwind City"},
{ str = "Accept #ACCEPTWolves at Our Heels#", y = 33.19, x = 7.71, QA = 226, zone = "Duskwood"},
{ str = "#DOQUEST*#Kill wolves along the N/NW river bank\n \nSpeak with Madame Eva \nAccept #ACCEPTThe Legend of Stalvan#  \nAccept #ACCEPTThe Totem of Infliction#", y = 45.29, x = 75.81, QA = {66,101}, zone = "Duskwood"},
{ str = "Set your hearth to  Duskwood", y = 43.4, x = 73.9, zone = "Duskwood", typ = "home"},
{ str = "Head towards the Town Hall \nAccept #ACCEPTThe Night Watch#", y = 46.89, x = 73.59, QA = 56, zone = "Duskwood"},
{ str = "Turn in #TURNINThe Legend of Stalvan# pt.1  \nAccept #ACCEPTThe Legend of Stalvan# pt.2", y = 46.85, x = 72.53, QA = 67, zone = "Duskwood", QT = 66},
{ str = "Speak with Elaine Carevin \nAccept #ACCEPTRaven Hill#  \nAccept #ACCEPTDeliveries to Sven#  \nAccept #ACCEPTThe Hermit#", y = 48.69, x = 75.33, QA = {165,164,163}, zone = "Duskwood"},
{ str = "Get the  Duskwood Flight path", typ = "fp"},
{ str = "Buy a Bronze Tube if you don't have one\n \nAccept #ACCEPTLook To The Stars#", y = 48.02, x = 79.8, QA = 174, zone = "Duskwood"},
{ str = "Turn in #TURNINLook To The Stars#  \nSkip this step if you haven't found a bronze tube yet", y = 48.02, x = 79.8, zone = "Duskwood", QT = 174},
{ str = "Accept #ACCEPTLook To The Stars#", y = 48.02, x = 79.8, QA = 175, zone = "Duskwood"},
{ str = " Head south towards the chapel  \nTurn in #TURNINLook To The Stars#  \nAccept #ACCEPTLook To The Stars#", y = 59.02, x = 81.46, QA = 177, zone = "Duskwood", QT = 175},
{ str = "#DOQUEST*#Kill the Insane Ghoul inside the chapel", y = 71.47, x = 81.2, zone = "Duskwood", QC = 177},
{ str = "Do #DOQUESTThe Night Watch#", y = 70.77, x = 79.4, zone = "Duskwood", QC = 56},
{ str = "Accept #ACCEPTEight-Legged Menaces#", y = 67.02, x = 45.12, QA = 245, zone = "Duskwood"},
{ str = "Turn in #TURNINRaven Hill#  \nAccept #ACCEPTJitters' Growling Gut#", y = 56.36, x = 18.37, QA = 5, zone = "Duskwood", QT = 163},
{ str = "#DOQUEST*#Kill spiders along the western river bank \nDon't go out of your way to do this quest, skip it if necessary\n \nTurn in #TURNINDeliveries to Sven#  \nAccept #ACCEPTSven's Revenge# ", y = 34.06, x = 7.78, QA = 95, zone = "Duskwood", QT = 164},
{ str = "Turn in #TURNINWolves at Our Heels#", y = 33.19, x = 7.71, zone = "Duskwood", QT = 226},
{ str = "Turn in #TURNINThe Hermit#  \nAccept #ACCEPTSupplies from Darkshire#", y = 31.46, x = 28.1, QA = 148, zone = "Duskwood", QT = 165},
{ str = "Grind mobs until your Hearthstone cooldown is < 5min  \nMake sure you have Gooey Spider Legx6"},
{ str = "#DOQUEST*#Head to westfall and look out for dust devils \n \n Get the  Westfall Flight Path", y = 52.63, x = 56.55, zone = "Westfall", typ = "fp"},
{ str = "#DOQUEST*#Look out for dust devils\n \nMake sure you have at least 1 bag slot \nClick on the footlocker on the ground  \nTurn in #TURNINThe Legend of Stalvan#  \nAccept #ACCEPTThe Legend of Stalvan#", y = 66.72, x = 41.51, QA = 68, zone = "Westfall", QT = 67, unitscan = "DUST DEVIL"},
{ str = "Hearth back to  Duskwood\n \nTurn in #TURNINJitters' Growling Gut#  \nAccept #ACCEPTDusky Crab Cakes#", y = 43.45, x = 73.88, QA = 93, zone = "Duskwood", QT = 5},
{ str = "Turn in #TURNINThe Night Watch#  \nAccept #ACCEPTThe Night Watch#", y = 46.89, x = 73.59, QA = 57, zone = "Duskwood", QT = 56},
{ str = "Turn in #TURNINThe Legend of Stalvan#  \nAccept #ACCEPTThe Legend of Stalvan#", y = 46.85, x = 72.53, QA = 69, zone = "Duskwood", QT = 68},
{ str = "Turn in #TURNINSupplies from Darkshire#  \nAccept #ACCEPTGhost Hair Thread#", y = 45.29, x = 75.81, QA = 149, zone = "Duskwood", QT = 148},
{ str = "Head to Redridge \nGet the  Redridge Mountains FP", y = 19.77, x = 81.83, zone = "Duskwood", typ = "fp"},
{ str = "Accept #ACCEPTBlackrock Bounty#", y = 57.85, x = 31.53, QA = 128, zone = "Redridge Mountains"},
{ str = "Head to Lakeshire \nAccept #ACCEPTBlackrock Menace#", y = 48.96, x = 33.5, QA = 20, zone = "Redridge Mountains"},
{ str = "Accept #ACCEPTAn Unwelcome Guest#", y = 46.32, x = 21.85, QA = 34, zone = "Redridge Mountains"},
{ str = "Do #DOQUESTAn Unwelcome Guest#", y = 49.3, x = 15.68, zone = "Redridge Mountains", QC = 34},
{ str = "Turn in #TURNINAn Unwelcome Guest#", y = 46.32, x = 21.85, zone = "Redridge Mountains", QT = 34},
{ str = "Accept #ACCEPTSelling Fish#  \nAccept #ACCEPTMurloc Poachers#", y = 47.29, x = 27.34, QA = {127,150}, zone = "Redridge Mountains"},
{ str = "#DOQUEST*##DOQUEST*#Kill murlocs\n \n#DOQUEST*#Prioritize killing orcs \nOnce you clear the camp, kill murlocs southwest while you wait for respawns", y = 43.51, x = 61.76, zone = "Redridge Mountains", QC = 20},
{ str = "Turn in #TURNINBlackrock Menace#", y = 48.96, x = 33.5, zone = "Redridge Mountains", QT = 20},
{ str = "Click on the wanted poster  \nAccept #ACCEPTWanted: Lieutenant Fangore#\n \nTurn in #TURNINSelling Fish#  \nTurn in #TURNINMurloc Poachers#", y = 47.38, x = 27.72, zone = "Redridge Mountains", QT = {127,150}},
{ str = "Click on the wanted poster  \nAccept #ACCEPTWanted: Lieutenant Fangore#", y = 46.43, x = 26.75, QA = 180, zone = "Redridge Mountains"},
{ str = "Go inside the town hall  \nAccept #ACCEPTSolomon's Law#", y = 44.26, x = 29.71, QA = 91, zone = "Redridge Mountains"},
{ str = "Remember to keep checking the engineering supplies NPC in duskwood if you haven't purchased a bronze tube yet\n \nFly to  Duskwood", typ = "fly"},

        }
    },

-----------22-23 Stonetalon Mountains
    --[203] = {
    [2223] = {
        title = "25-27 Duskwood/Redridge",
        --n = "22-23 Stonetalon Mountains",
        --pID = 202, nID = 204,
        --itemCount = 10,
        items = {


{ str = "Head to the small farmhouse southeast of Darkshire \nTurn in #TURNINGhost Hair Thread#  \nAccept #ACCEPTReturn the Comb#", y = 59.08, x = 81.98, QA = 154, zone = "Duskwood", QT = 149},
{ str = "Turn in #TURNINReturn the Comb#  \nAccept #ACCEPTDeliver the Thread#", y = 45.29, x = 75.81, QA = 157, zone = "Duskwood", QT = 154},
{ str = "Turn in #TURNINSven's Revenge#  \nAccept #ACCEPTSven's Camp#", y = 77.71, x = 49.85, QA = 230, zone = "Duskwood", QT = 95},
{ str = "Turn in #TURNINEight-Legged Menaces#\n#TURNIN*#Kill spiders\n \nTurn in #TURNINDeliver the Thread#  \nAccept #ACCEPTZombie Juice#", y = 31.46, x = 28.1, QA = 158, zone = "Duskwood", QT = 157},
{ str = "Turn in #TURNINSven's Camp#  \nAccept #ACCEPTThe Shadowy Figure#", y = 34.06, x = 7.78, QA = 262, zone = "Duskwood", QT = 230},
{ str = "Finish off #DOQUESTDusky Crab Cakes#", y = 43.45, x = 73.88, zone = "Duskwood", QC = { [93] = 1}},
{ str = "Grind to 25 + 85%"},
{ str = "Run to Elwynn Forest \n \nTurn in #TURNINThe Legend of Stalvan#  \nAccept #ACCEPTThe Legend of Stalvan#", y = 66, x = 43.7, QA = 70, zone = "Elwynn Forest", QT = 69},
{ str = "Run up the stairs \nLoot the #DOQUESTchest# on the floor", zone = "Duskwood", QC = 70},
{ str = "Turn in #TURNINDevils in Westfall#\n \nAccept #ACCEPTA Noble Brew#", y = 78.66, x = 26.44, QA = 335, zone = "Stormwind City"},
{ str = "Turn in #TURNINThe Legend of Stalvan#  \nAccept #ACCEPTThe Legend of Stalvan# ", y = 61.93, x = 29.56, QA = 72, zone = "Stormwind City", QT = 70},
{ str = "Click on the crate nearby  \nTurn in #TURNINThe Legend of Stalvan#  \nAccept #ACCEPTThe Legend of Stalvan#", y = 61.52, x = 29.44, QA = 74, zone = "Stormwind City", QT = 72},
{ str = "Turn in #TURNINReturn to Kristoff#\n \n Fly to  Duskwood", y = 62.14, x = 66.29, zone = "Stormwind City", typ = "fly"},
{ str = "Turn in #TURNINLook To The Stars#  \nAccept #ACCEPTLook To The Stars#", y = 48.02, x = 79.8, QA = 181, zone = "Duskwood", QT = 177},
{ str = "Speak with Madame Eva \nTurn in #TURNINThe Shadowy Figure#  \nAccept #ACCEPTThe Shadowy Search Continues#", y = 45.29, x = 75.81, QA = 265, zone = "Duskwood", QT = 262},
{ str = "Turn in #TURNINThe Shadowy Search Continues#  \nAccept #ACCEPTInquire at the Inn#", y = 46.85, x = 72.53, QA = 266, zone = "Duskwood", QT = 265},
{ str = "Turn in #TURNINZombie Juice#  \nAccept #ACCEPTGather Rot Blossoms#  \n Turn in #TURNINInquire at the Inn#  \nAccept #ACCEPTFinding the Shadowy Figure#", y = 44.48, x = 73.77, QA = {156,453}, zone = "Duskwood", QT = {158,266}},
{ str = "Turn in #TURNINDusky Crab Cakes#  \nAccept #ACCEPTReturn to Jitters#", y = 43.45, x = 73.88, QA = 240, zone = "Duskwood", QT = 93},
{ str = "#DOQUEST*##DOQUEST*#Kill skeletons at the Raven Hill Cemetery", y = 44.76, x = 22.36, zone = "Duskwood", QC = { [57] = 0, [156] = 0}},
{ str = "Turn in #TURNINFinding the Shadowy Figure#  \nAccept #ACCEPTReturn to Sven#  \nTurn in #TURNINReturn to Jitters#", y = 56.36, x = 18.37, QA = 268, zone = "Duskwood", QT = {453,240}},
{ str = "Turn in #TURNINReturn to Sven#  \nAccept #ACCEPTProving Your Worth#", y = 34.06, x = 7.78, QA = 323, zone = "Duskwood", QT = 268},
{ str = "Do #DOQUESTProving Your Worth#", y = 36.85, x = 15.93, zone = "Duskwood", QC = 323},
{ str = "Turn in #TURNINProving Your Worth#  \nAccept #ACCEPTSeeking Wisdom#", y = 34.06, x = 7.78, QA = 269, zone = "Duskwood", QT = 323},
{ str = "Grind mobs until your HS is off cooldown, Hearth to  Darkshire\n \nIf you haven't found a bronze tube, save your HS cooldown and fly from Westfall to  Duskwood", typ = "fly"},
{ str = "Turn in #TURNINGather Rot Blossoms#  \nAccept #ACCEPTJuice Delivery#", y = 44.48, x = 73.77, QA = 159, zone = "Duskwood", QT = 156},
{ str = "Turn in #TURNINThe Night Watch#  \nAccept #ACCEPTThe Night Watch#", y = 46.89, x = 73.59, QA = 58, zone = "Duskwood", QT = 57},
{ str = "If you managed to find An Old History Book right click it \nAccept #ACCEPTAn Old History Book#  \nSkip this step if you don't have it\n \nFly to  Redridge", typ = "fly"},
{ str = "Kill #DOQUEST*#Gnolls, loot their pendants\n \nSet your HS to redridge if you haven't found a bronze tube \nSkip this step if you purchased it already", typ = "home"},
{ str = "Accept #ACCEPTBlackrock Bounty#", y = 57.85, x = 31.53, QA = 128, zone = "Redridge Mountains"},
{ str = "Accept #ACCEPTTharil'zun#", y = 48.96, x = 33.5, QA = 19, zone = "Redridge Mountains"},
{ str = "Accept #ACCEPTHowling in the Hills#\n \nGo inside the town hall  \nAccept #ACCEPTSolomon's Law#", y = 44.26, x = 29.71, QA = 91, zone = "Redridge Mountains"},
{ str = "Click on the wanted poster \nAccept #ACCEPTWanted: Lieutenant Fangore#", y = 46.43, x = 26.75, QA = 180, zone = "Redridge Mountains"},
{ str = "Do #DOQUESTWanted: Lieutenant Fangore#", y = 37.05, x = 80.17, zone = "Redridge Mountains", QC = 180},
{ str = "Turn in #TURNINA Watchful Eye# at the lion statue\n \nFinish off #DOQUESTSolomon's Law#", y = 36.31, x = 77.52, zone = "Redridge Mountains", QC = 91},
{ str = "Pet pull #DOQUESTTharil'zun#, kite him towards burning steppes", y = 55.07, x = 71.4, zone = "Redridge Mountains", QC = 19, unitscan = "THARIL'ZUN"},
{ str = "Do #DOQUESTBlackrock Bounty#", y = 13.2, x = 28.89, zone = "Redridge Mountains", QC = 128},
{ str = "If you haven't found a bronze tube, run to burning steppes, die on purpose, buy a bronze tube at flame's crest and hearth back to Redridge\n \nAccept #ACCEPTMissing In Action#", y = 12.6, x = 28.4, QA = 219, zone = "Redridge Mountains"},
{ str = "Turn in #TURNINTharil'zun#", y = 48.96, x = 33.5, zone = "Redridge Mountains", QT = 19},
{ str = "Turn in #TURNINMissing In Action#", y = 48.96, x = 33.5, zone = "Redridge Mountains", QT = 219},
{ str = "Turn in #TURNINSolomon's Law#  \nTurn in #TURNINWanted: Lieutenant Fangore#", y = 44.26, x = 29.71, zone = "Redridge Mountains", QT = {91,180}},
{ str = "Turn in #TURNINBlackrock Bounty#", y = 57.85, x = 31.53, zone = "Redridge Mountains", QT = 128},
{ str = "Fly to  Stormwind", typ = "fly"},


        }
    },

-----------23-24 Darkshore
    --[204] = {
    [2324] = {
        title = "27-29 Wetlands/Hillsbrad",
        --n = "23-24 Darkshore",
        --pID = 203, nID = 205,
        --itemCount = 20,
        items = {



{ str = "Deposit the follwing items: \nA Torn Journal Page \nBottle of Zombie Juice \nSkeleton Finger \nVial of Spider Venom \n \nWithdraw from your bank: \nGobbler's Head \nBundle of Crocolisk Skins \nYoung Crocolisk Skin (x4) \n \nFly to Stormwind \nTurn in #TURNINSeeking Wisdom#  \nAccept #ACCEPTThe Doomed Fleet#", y = 27.88, x = 39.11, QA = 270, zone = "Stormwind City", QT = 269},
{ str = "Accept #ACCEPTTinkmaster Overspark#", y = 30.91, x = 40.55, QA = 2923, zone = "Stormwind City"},
{ str = "Take the tram to Ironforge \n \nTurn in #TURNINAn Old Colleague#", QT = 1072, zone = "Stonetalon Mountains"},
{ str = "Turn in #TURNINTinkmaster Overspark#", y = 50.32, x = 69.54, zone = "Ironforge", QT = 2923},
{ str = "Fly to  Wetlands", typ = "fly"},
{ str = "Turn in #TURNINThe Doomed Fleet#  \nSkip the follow up", QT = 270, zone = "Duskwood"},
{ str = " Set your Hearthstone to Wetlands", typ = "home"},
{ str = "Go upstairs and accept #ACCEPTThe Absent Minded Prospector#", y = 60.43, x = 10.84, QA = 943, zone = "Wetlands"},
{ str = "Accept #ACCEPTThe Cursed Crew#", y = 59.66, x = 10.89, QA = 289, zone = "Wetlands"},
{ str = "Accept #ACCEPTDigging Through the Ooze#", y = 57.99, x = 11.79, QA = 470, zone = "Wetlands"},
{ str = "Turn in #TURNINClaws from the Deep#  \nAccept #ACCEPTReclaiming Goods#", y = 58.53, x = 8.3, QA = 281, zone = "Wetlands", QT = 279},
{ str = "Turn in #TURNINDaily Delivery#  \nTurn in #TURNINYoung Crocolisk Skins#  \nAccept #ACCEPTApprentice's Duties#", y = 55.73, x = 8.54, QA = 471, zone = "Wetlands", QT = {469,484}},
{ str = "Turn in #TURNINReport to Captain Stoutfist#\n \nEnter the keep and head upstairs  \nAccept #ACCEPTWar Banners#", y = 57.48, x = 9.86, QA = 464, zone = "Wetlands"},
{ str = "Accept #ACCEPTFall of Dun Modr#", y = 55.89, x = 10.84, QA = 472, zone = "Wetlands"},
{ str = "Accept #ACCEPTIn Search of The Excavation Team#", y = 52.13, x = 11.5, QA = 305, zone = "Wetlands"},
{ str = "Turn in #TURNINReclaiming Goods#  \nAccept #ACCEPTThe Search Continues#", y = 41.37, x = 13.52, QA = 284, zone = "Wetlands", QT = 281},
{ str = "Turn in #TURNINThe Search Continues#  \nAccept #ACCEPTSearch More Hovels#", y = 38.22, x = 13.6, QA = 285, zone = "Wetlands", QT = 284},
{ str = "Turn in #TURNINSearch More Hovels#  \nAccept #ACCEPTReturn the Statuette#", y = 34.81, x = 13.94, QA = 286, zone = "Wetlands", QT = 285},
{ str = "Start working on #DOQUESTApprentice's Duties#\n \n#DOQUEST*# Kill ghosts, enter the ship by the hole on the hull and kill Snellig", y = 23.93, x = 14.72, zone = "Wetlands", QC = 289},
{ str = "Kill #DOQUESTGnolls# on your way to other objectives\n \nKill #DOQUESTOrcs#", y = 42.62, x = 43.14, zone = "Wetlands", QC = 464},
{ str = "Head towards the mountain shortcut  \nAccept #ACCEPTOrmer's Revenge#", y = 46.7, x = 39.52, QA = 294, zone = "Wetlands"},
{ str = "Turn in #TURNINIn Search of The Excavation Team#  \nAccept #ACCEPTIn Search of The Excavation Team#  \nAccept #ACCEPTUncovering the Past#", y = 52.33, x = 38.9, QA = {306,299}, zone = "Wetlands", QT = 305},
{ str = "#DOQUEST*# Loot the fossil on the ground", zone = "Darkshore", QC = { [943] = 2}},
{ str = "Finish off #DOQUESTFire Taboo#", y = 33.5, x = 44.14, zone = "Wetlands", QC = 277},
{ str = "Turn in #TURNINFire Taboo#  \nAccept #ACCEPTBlisters on The Land#", y = 40.4, x = 56.37, QA = 275, zone = "Wetlands", QT = 277},
{ str = "#DOQUEST*# Loot a Musquash Root by the base of the waterfall", y = 75.31, x = 64.78, zone = "Wetlands", QC = { [335] = 2}},
{ str = "Hearth to  Menethil Harbor\n \nTurn in #TURNINThe Cursed Crew#  \nAccept #ACCEPTLifting the Curse#", y = 59.66, x = 10.89, QA = 290, zone = "Wetlands", QT = 289},
{ str = "Turn in #TURNINReturn the Statuette# ", y = 58.53, x = 8.3, zone = "Wetlands", QT = 286},
{ str = "Turn in #TURNINDigging Through the Ooze#", y = 57.99, x = 11.79, zone = "Wetlands", QT = 470},
{ str = "Turn in #TURNINWar Banners#  \nAccept #ACCEPTNek'rosh's Gambit#", y = 57.48, x = 9.86, QA = 465, zone = "Wetlands", QT = 464},
{ str = "Turn in #TURNINIn Search of The Excavation Team#", y = 52.13, x = 11.5, zone = "Wetlands", QT = 306},
{ str = "#DOQUEST*# Kill Raptors", y = 47.4, x = 25.58, zone = "Wetlands", QC = 294},
{ str = "Turn in #TURNINOrmer's Revenge#  \nAccept #ACCEPTOrmer's Revenge#", y = 50.88, x = 38.17, QA = 295, zone = "Wetlands", QT = 294},
{ str = "#DOQUEST*# Search for the relics at the digsite \n \n#DOQUEST*#Kill Raptors", y = 49.95, x = 34.71, zone = "Wetlands", QC = 295},
{ str = "#DOQUEST*#Kill raptors\n \nTurn in #TURNINOrmer's Revenge#  \nAccept #ACCEPTOrmer's Revenge#", y = 50.88, x = 38.17, QA = 296, zone = "Wetlands", QT = 295},
{ str = "Turn in #TURNINUncovering the Past# \n \n#DOQUEST*# Kill Sarltooth", y = 51.5, x = 33.25, zone = "Wetlands", QC = 296},
{ str = "Finish off #DOQUESTUncovering the Past#", y = 44.5, x = 35.25, zone = "Wetlands", QC = 299},
{ str = "Turn in #TURNINOrmer's Revenge#  \nTurn in #TURNINUncovering the Past#", y = 50.88, x = 38.17, zone = "Wetlands", QT = {296,299}},
{ str = "#DOQUEST*# Look for Fen Creepers along the river stream \n \nEnter the ship by the broken mast  \nKill #DOQUESTCaptain Halyndor# ", y = 23.6, x = 15.44, zone = "Wetlands", QC = 290},
{ str = "Dive to the bottom of the ship  \nTurn in #TURNINLifting the Curse#   \nAccept #ACCEPTThe Eye of Paleth#", y = 24.04, x = 14.37, QA = 292, zone = "Wetlands", QT = 290},
{ str = "Finish off #DOQUESTApprentice's Duties#", y = 26.68, x = 17.27, zone = "Wetlands", QC = 471},
{ str = "Finish off #DOQUESTBlisters on The Land#", y = 33.25, x = 37.86, zone = "Wetlands", QC = 275},
{ str = "Turn in #TURNINNek'rosh's Gambit#", y = 47.01, x = 47.45, zone = "Wetlands", QT = 465},
{ str = "Accept #ACCEPTDefeat Nek'rosh# ", y = 47.01, x = 47.45, QA = 474, zone = "Wetlands"},
{ str = "Kill #DOQUESTNek'rosh# \n \nTurn in #TURNINBlisters on The Land#", y = 40.4, x = 56.37, zone = "Wetlands", QT = 275},
{ str = "Kill #DOQUESTSlimes#", y = 25.61, x = 44.25, zone = "Wetlands", QC = 470},
{ str = "Turn in #TURNINFall of Dun Modr#  \nAccept #ACCEPTThe Thandol Span#", y = 18.25, x = 49.8, QA = 631, zone = "Wetlands", QT = 472},
{ str = "Turn in #TURNINThe Thandol Span#  \nAccept #ACCEPTThe Thandol Span#", y = 93.07, x = 45.65, QA = 632, zone = "Arathi Highlands", QT = 631},
{ str = "Turn in #TURNINThe Thandol Span#  \nAccept #ACCEPTThe Thandol Span#", y = 18.21, x = 49.91, QA = 633, zone = "Wetlands", QT = 632},
{ str = "Jump down the bridge and accept #ACCEPTMacKreel's Moonshine# \nIt's a very precise jump if you don't have any kind of movement speed increase or slow fall, skip this step if you don't know how to do it.", y = 92.64, x = 43.24, QA = 647, zone = "Arathi Highlands"},
{ str = "Loot the #ACCEPTWaterlogged Envelope# underwater \n \n#DOQUEST*# Click on the cart full of explosives", y = 88.04, x = 48.79, zone = "Arathi Highlands", QC = 633},
{ str = "Turn in #TURNINThe Thandol Span#  \nAccept #ACCEPTPlea To The Alliance#", y = 18.21, x = 49.91, QA = 634, zone = "Wetlands", QT = 633},
{ str = "Turn in #TURNINPlea To The Alliance#", y = 47.55, x = 45.83, zone = "Arathi Highlands", QT = 634},
{ str = "Get the  Arathi Highlands FP", typ = "fp"},
{ str = " Buy all 3 first aid books inside Stromgarde if you are leveling first aid\n \nHead to Southshore", y = 29.74, x = 20.08, zone = "Arathi Highlands"},
{ str = "Turn in #TURNINMacKreel's Moonshine#", y = 58.73, x = 52.13, zone = "Hillsbrad Foothills", QT = 647},
{ str = "Get the  Southshore FP", typ = "fp"},
{ str = "Do the murloc quests in Southshore or farm turtle meat until you are 55% into level 29 \nStable your pet and head east  \nTame a spider, learn bite rank 4 \n \nKill turtles along the river and save turtle meat for later, don't go out of your way to kill them"},
{ str = "Hearth to Menethil Harbor\n \nTurn in #TURNINThe Eye of Paleth#  \nAccept #ACCEPTCleansing the Eye#", y = 60.59, x = 10.58, QA = 293, zone = "Wetlands", QT = 292},
{ str = "Accept #ACCEPTLightforge Iron#", QA = 321, zone = "Duskwood"},
{ str = "Go upstairs  \nTurn in #TURNINThe Absent Minded Prospector#", y = 60.43, x = 10.84, zone = "Wetlands", QT = 943},
{ str = "Turn in #TURNINLightforge Iron#  \nAccept #ACCEPTThe Lost Ingots#", y = 64.19, x = 12.1, QA = 324, zone = "Wetlands", QT = 321},
{ str = "#DOQUEST*# Kill murlocs", y = 69.7, x = 9.54, zone = "Wetlands", QC = 324},
{ str = "Grind until you are 15k xp away from level 30"},
{ str = "Turn in #TURNINApprentice's Duties#", y = 55.73, x = 8.54, zone = "Wetlands", QT = 471},
{ str = "Turn in #TURNINDefeat Nek'rosh#", y = 57.48, x = 9.86, zone = "Wetlands", QT = 474},
{ str = "Turn in #TURNINThe Lost Ingots#  \nAccept #ACCEPTBlessed Arm#", y = 60.59, x = 10.58, QA = 322, zone = "Wetlands", QT = 324},
{ str = "Fly to  Ironforge", typ = "fly"},
        }
    },

-----------24-25 Ashenvale
    --[205] = {
    [2425] = {
        title = "29-32 Duskwood/STV",
        --n = "24-25 Ashenvale",
        --pID = 204, nID = 206,
        --itemCount = 16,
        items = {
            




{ str = "Withdraw the follwing: \nA Torn Journal Page \nBottle of Zombie Juice \nSkeleton Finger \nVial of Spider Venom \nAn Old History Book (if you have it) "},
{ str = "Fly to Ironforge \nTurn in #TURNINSully Balloo's Letter#  \nWait for the RP sequence \nAccept #ACCEPTSara Balloo's Plea#", y = 67.3, x = 63.5, QA = 683, zone = "Ironforge", QT = 637},
{ str = "Turn in #TURNINSara Balloo's Plea#  \nAccept #ACCEPTA King's Tribute#", y = 56.19, x = 39.09, QA = 686, zone = "Ironforge", QT = 683},
{ str = "Turn in #TURNINA King's Tribute#  \nAccept #ACCEPTA King's Tribute#", y = 88.05, x = 39.03, QA = 689, zone = "Ironforge", QT = 686},
{ str = "Train pet skills \nMake sure you have frost/nature resistance maxed out on your pet\n \nAccept #ACCEPTThe Brassbolts Brothers#", y = 94, x = 72.72, QA = 1179, zone = "Ironforge"},
{ str = "Take the tram to Stormwind \n \nDeposit the following items: \nMusquash Root \nCrate of Crash Helmets \nTurtle Meat "},
{ str = "Turn in #TURNINBlessed Arm#  \nAccept #ACCEPTArmed and Ready#", y = 12.06, x = 51.75, QA = 325, zone = "Stormwind City", QT = 322},
{ str = "If you get level 30 turning in the next few quests in SW, remember to buy class/pet skills\n \nTurn in #TURNINCleansing the Eye#", y = 27.2, x = 39.6, zone = "Stormwind City", QT = 293},
{ str = "Accept #ACCEPTThe Missing Diplomat# pt.1 ", y = 25.89, x = 38.72, QA = 1274, zone = "Stormwind City"},
{ str = "Turn in #TURNINThe Missing Diplomat# pt.1  \nAccept #ACCEPTThe Missing Diplomat# pt.2", y = 25.45, x = 78.3, QA = 1241, zone = "Stormwind City", QT = 1274},
{ str = "Turn in #TURNINThe Missing Diplomat# pt.2  \nAccept #ACCEPTThe Missing Diplomat# pt.3", y = 78.42, x = 73.17, QA = 1242, zone = "Stormwind City", QT = 1241},
{ str = "Turn in #TURNINThe Missing Diplomat# pt.3   \nAccept #ACCEPTThe Missing Diplomat# pt.4", y = 64.17, x = 59.9, QA = 1243, zone = "Stormwind City", QT = 1242},
{ str = "Fly to  Duskwood", typ = "fly"},
{ str = "Accept #ACCEPTLook To The Stars#  \nTurn in #TURNINLook To The Stars#  \nSkip this step if you haven't found a bronze tube", y = 48.02, x = 79.8, QA = 174, zone = "Duskwood", QT = 174},
{ str = "Accept #ACCEPTLook To The Stars# pt.2", y = 48.02, x = 79.8, QA = 175, zone = "Duskwood"},
{ str = " Head south towards the chapel  \nTurn in #TURNINLook To The Stars# pt.2  \nAccept #ACCEPTLook To The Stars# pt.3", y = 59.02, x = 81.46, QA = 177, zone = "Duskwood", QT = 175},
{ str = "#DOQUEST*#Kill the Insane Ghoul inside the chapel", y = 71.47, x = 81.2, zone = "Duskwood", QC = 177},
{ str = "Turn in #TURNINLook To The Stars# pt.3", y = 48.02, x = 79.8, zone = "Duskwood", QT = 177},
{ str = "Accept #ACCEPTLook To The Stars# pt.4", y = 48.02, x = 79.8, QA = 181, zone = "Duskwood"},
{ str = "Accept #ACCEPTWorgen in the Woods#", y = 47.56, x = 75.75, QA = 173, zone = "Duskwood"},
{ str = "Accept #ACCEPTThe Night Watch#", y = 46.89, x = 73.59, QA = 58, zone = "Duskwood"},
{ str = "Set your HS to  Darkshire", typ = "home"},
{ str = "Turn in #TURNINThe Missing Diplomat# pt.4  \nAccept #ACCEPTThe Missing Diplomat# pt.5", QT = 1243, QA = 1244, zone = "Stormwind City"},
{ str = "Do #DOQUESTWorgen in the Woods#", y = 41.6, x = 63, zone = "Duskwood", QC = 173},
{ str = "Turn in #TURNINWorgen in the Woods# pt.1 \nAccept #ACCEPTWorgen in the Woods# pt.2", y = 47.56, x = 75.75, QA = 221, zone = "Duskwood", QT = 173},
{ str = "Do #DOQUESTWorgen in the Woods# pt.2", y = 45.3, x = 61.8, zone = "Duskwood", QC = 221},
{ str = "Head northeast to Elwynn Forest \nTurn in #TURNINThe Legend of Stalvan# pt.7  \nAccept #ACCEPTThe Legend of Stalvan# pt.8", y = 69.37, x = 84.6, QA = 75, zone = "Elwynn Forest", QT = 74},
{ str = "#DOQUEST*#Loot the chest inside the house", zone = "Duskwood", QC = 75},
{ str = "Turn in #TURNINThe Legend of Stalvan# pt.8  \nAccept #ACCEPTThe Legend of Stalvan# pt.9", QT = 75, QA = 78, zone = "Duskwood"},
{ str = "Turn in #TURNINJuice Delivery#  \nAccept #ACCEPTGhoulish Effigy# ", y = 31.46, x = 28.1, QA = 133, zone = "Duskwood", QT = 159},
{ str = "Finish off #DOQUESTThe Totem of Infliction#\n \n#DOQUEST*##DOQUEST*# Kill Ghouls/Plague Spreaders", y = 32.9, x = 24.26, zone = "Duskwood", QC = { [58] = 0, [133] = 0}},
{ str = "Turn in #TURNINGhoulish Effigy#  \nAccept #ACCEPTOgre Thieves#", y = 31.46, x = 28.1, QA = 134, zone = "Duskwood", QT = 133},
{ str = "#DOQUEST*# Loot the chest inside the farmhouse", y = 72, x = 24.1, zone = "Duskwood", QC = 1244},
{ str = "#DOQUEST*# Click on the crate on the ground", y = 76.35, x = 33.41, zone = "Duskwood", QC = 134},
{ str = "#DOQUEST*# Kill Zzarc'Vul", y = 83.78, x = 36.81, zone = "Duskwood", QC = 181},
{ str = "Turn in #TURNINOgre Thieves#  \nAccept #ACCEPTNote to the Mayor#", y = 31.46, x = 28.1, QA = 160, zone = "Duskwood", QT = 134},
{ str = "Accept #ACCEPTThe Weathered Grave#", y = 29.07, x = 17.72, QA = 225, zone = "Duskwood"},
{ str = "Accept #ACCEPTProving Your Worth#", y = 34.06, x = 7.78, QA = 323, zone = "Duskwood"},
{ str = "Do #DOQUESTProving Your Worth#", y = 36.85, x = 15.93, zone = "Duskwood", QC = 323},
{ str = "Turn in #TURNINProving Your Worth#  \nAccept #ACCEPTSeeking Wisdom#", y = 34.06, x = 7.78, QA = 269, zone = "Duskwood", QT = 323},
{ str = "Turn in #TURNINArmed and Ready#  \nAccept #ACCEPTMorbent Fel#", y = 34.06, x = 7.78, QA = 55, zone = "Duskwood", QT = 325},
{ str = "Hearth back to  Darkshire\nMake sure you have 2 stacks of food/water \nBuy extra stacks of ammo, long grinding session ahead\n \nTurn in #TURNINThe Legend of Stalvan# pt.9  \nAccept #ACCEPTThe Legend of Stalvan# pt.10", y = 44.48, x = 73.77, QA = 79, zone = "Duskwood", QT = 78},
{ str = "Turn in #TURNINThe Night Watch# pt.3  \nTurn in #TURNINThe Legend of Stalvan# pt.10  \nAccept #ACCEPTThe Legend of Stalvan# pt.11", y = 46.89, x = 73.59, QA = 80, zone = "Duskwood", QT = {58,79}},
{ str = "Turn in #TURNINThe Legend of Stalvan# pt.11  \nAccept #ACCEPTThe Legend of Stalvan# pt.12", y = 46.85, x = 72.53, QA = 97, zone = "Duskwood", QT = 80},
{ str = "Turn in #TURNINThe Weathered Grave#  \nAccept #ACCEPTMorgan Ladimore#", y = 47.61, x = 72.64, QA = 227, zone = "Duskwood", QT = 225},
{ str = "Turn in #TURNINNote to the Mayor#  \nAccept #ACCEPTTranslate Abercrombie's Note#", y = 46.41, x = 71.93, QA = 251, zone = "Duskwood", QT = 160},
{ str = "Turn in #TURNINTranslate Abercrombie's Note#  \nAccept #ACCEPTWait for Sirra to Finish#  \nTurn in #TURNINWait for Sirra to Finish#  \nAccept #ACCEPTTranslation to Ello#", y = 47.61, x = 72.64, QA = {401,252}, zone = "Duskwood", QT = {251,401}},
{ str = "Talk to the mayor again \nTurn in #TURNINTranslation to Ello# ", y = 46.41, x = 71.93, zone = "Duskwood", QT = 252},
{ str = "Accept #ACCEPTBride of the Embalmer#", y = 46.41, x = 71.93, QA = 253, zone = "Duskwood"},
{ str = "Turn in #TURNINThe Legend of Stalvan# pt.12  \nAccept #ACCEPTThe Legend of Stalvan# pt.13  \nTurn in #TURNINMorgan Ladimore#  \nAccept #ACCEPTMor'Ladim#", y = 46.89, x = 73.59, QA = {98,228}, zone = "Duskwood", QT = {97,227}},
{ str = "Turn in #TURNINThe Missing Diplomat# pt.5 \nAccept #ACCEPTThe Missing Diplomat# pt.6", QT = 1244, QA = 1245, zone = "Stormwind City"},
{ str = "#DOQUEST*#Kill Stalvan inside the farmhouse \n#DOQUEST*#Loot the small flower at the farm", y = 36.2, x = 77.3, zone = "Duskwood", QC = { [98] = 0, [335] = 1}},
{ str = "Turn in #TURNINThe Legend of Stalvan#  \nTurn in #TURNINThe Totem of Infliction#", y = 45.29, x = 75.81, zone = "Duskwood", QT = {98,101}},
{ str = "Turn in #TURNINWorgen in the Woods# pt.2", y = 47.56, x = 75.75, zone = "Duskwood", QT = 221},
{ str = "Accept #ACCEPTWorgen in the Woods# pt.3", y = 47.56, x = 75.75, QA = 222, zone = "Duskwood"},
{ str = "Turn in #TURNINLook To The Stars#", y = 48.02, x = 79.8, zone = "Duskwood", QT = 181},
{ str = "#DOQUEST*#Kill Vile Fangs/Tanted Ones\n \nDo #DOQUESTWorgen in the Woods#", y = 80.3, x = 59.8, zone = "Duskwood", QC = 222},
{ str = "Grind mobs until you find An Old History Book \nAccept #ACCEPTAn Old History Book#\n \nGrind until you are anywhere between level 31.5 and level 32  \nKeep grinding until your HS cooldown is <25 minutes"},
{ str = "#DOQUEST*#Click on the grave to summon Eliza \nKill Eliza and loot her heart \n  \nTo avoid dealing with her skeleton adds use the wagon to jump on top of Abercrombie's shed ", y = 31, x = 28.8, zone = "Duskwood", QC = 253},
{ str = "#DOQUEST*#Equip Morbent's Bane in your off-hand  \nKill Morbent Fel \nPull with Eyes of the Beast, don't touch any mobs, let Morbent Fel and all his adds proxy aggro your pet so you can split pull him away", y = 33.4, x = 16.9, zone = "Duskwood", QC = 55},
{ str = "Turn in #TURNINMorbent Fel#", y = 34.06, x = 7.78, zone = "Duskwood", QT = 55},
{ str = "#DOQUEST*#Kill Mor'Ladim, kite him to STV \n(Level 35 elite roaming the cemetery)\n \nAccept #ACCEPTWelcome to the Jungle#  \nTurn in #TURNINWelcome to the Jungle#", y = 10.52, x = 35.66, QA = 583, zone = "Stranglethorn Vale", QT = 583, unitscan = "MOR'LADIM"},
{ str = "Accept #ACCEPTTiger Mastery# pt.1 \nAccept #ACCEPTPanther Mastery# pt.1", y = 10.61, x = 35.61, QA = {185,190}, zone = "Stranglethorn Vale"},
{ str = "Look out for Private Thorsen's RP event while you quest  \nHe patrols down the road every ~30 minutes  \n(#ACCEPT*##TURNINJungle Secrets#)\nDo #DOQUESTPanther Mastery# pt.1 \n \nDo #DOQUESTTiger Mastery# pt.1", y = 12.5, x = 35.4, zone = "Stranglethorn Vale", QC = 185},
{ str = "Finish off #DOQUESTPanther Mastery# pt.1", y = 12, x = 41.5, zone = "Stranglethorn Vale", QC = 190},
{ str = "Turn in #TURNINTiger Mastery# pt.1 \nAccept #ACCEPTTiger Mastery# pt.2", y = 10.61, x = 35.61, QA = 186, zone = "Stranglethorn Vale", QT = 185},
{ str = "Turn in #TURNINPanther Mastery# pt.1", y = 10.54, x = 35.55, zone = "Stranglethorn Vale", QT = 190},
{ str = "Hearth to Darkshire\n \nTurn in #TURNINMor'Ladim#  \nAccept #ACCEPTThe Daughter Who Lived#", y = 46.89, x = 73.59, QA = 229, zone = "Duskwood", QT = 228},
{ str = "Turn in #TURNINBride of the Embalmer#", y = 46.41, x = 71.93, zone = "Duskwood", QT = 253},
{ str = "Turn in #TURNINThe Daughter Who Lived#  \nAccept #ACCEPTA Daughter's Love# ", y = 46.08, x = 74.54, QA = 231, zone = "Duskwood", QT = 229},
{ str = "Turn in #TURNINWorgen in the Woods#  \nAccept #ACCEPTWorgen in the Woods#", y = 47.56, x = 75.75, QA = 223, zone = "Duskwood", QT = 222},
{ str = "Turn in #TURNINWorgen in the Woods#", y = 49.02, x = 75.32, zone = "Duskwood", QT = 223},
{ str = "Fly to  Stormwind", typ = "fly"},
{ str = "Withdraw the following items: \nCrate of Crash Helmets \nTurtle Meat \nMusquash Root \nAn Old History Book \n \nTurn in #TURNINThe Missing Diplomat# pt.6 \nAccept #ACCEPTThe Missing Diplomat# pt.7", y = 64.17, x = 59.9, QA = 1246, zone = "Stormwind City", QT = 1245},
{ str = "Turn in #TURNINThe Missing Diplomat# pt.7  \nAccept #ACCEPTThe Missing Diplomat# pt.8", y = 44.88, x = 70.53, QA = 1447, zone = "Stormwind City", QT = 1246},
{ str = "#DOQUEST*# Beat Dashel Stonefist", QC = 1447},
{ str = "Turn in #TURNINThe Missing Diplomat# pt.8 \nAccept #ACCEPTThe Missing Diplomat# pt.9", y = 44.88, x = 70.53, QA = 1247, zone = "Stormwind City", QT = 1447},
{ str = "Turn in #TURNINThe Missing Diplomat# pt.9  \nAccept #ACCEPTThe Missing Diplomat# pt.10", y = 64.17, x = 59.9, QA = 1248, zone = "Stormwind City", QT = 1247},
{ str = "Accept #ACCEPTMalin's Request#", y = 81.45, x = 39.76, QA = 690, zone = "Stormwind City"},
{ str = "Accept #ACCEPTJames Hyal# pt.1", y = 91.83, x = 40.62, QA = 1301, zone = "Stormwind City"},
{ str = "Turn in #TURNINA Noble Brew# pt.1  \nAccept #ACCEPTA Noble Brew# pt.2", y = 78.66, x = 26.44, QA = 336, zone = "Stormwind City", QT = 335},
{ str = "Turn in #TURNINSeeking Wisdom#  \nAccept #ACCEPTThe Doomed Fleet#", QT = 269, QA = 270, zone = "Duskwood"},
{ str = "Turn in #TURNINA Noble Brew# pt.2", y = 31.67, x = 75.22, zone = "Stormwind City", QT = 336},
{ str = "Turn in #TURNINAn Old History Book#  \nAccept #ACCEPTSouthshore# ", QT = 337, QA = 538, zone = "Duskwood"},
{ str = "You don't need to train skills if you already purchased your level 30 spells\nTake the Tram to Ironforge \n \nFly to  Wetlands", y = 47.7, x = 55.5, zone = "Ironforge", typ = "fly"},


        }
    },

-----------25-27 Wetlands
    --[206] = {
    [2526] = {
        title = "32-33 Hillsbrad/Alterac",
        --n = "25-27 Wetlands",
        --pID = 205, nID = 207,
        --itemCount = 53,
        items = {


{ str = "Head to Menethil Harbor\nTurn in #TURNINJames Hyal# pt.1  \nAccept #ACCEPTJames Hyal# pt.2\nTurn in #TURNINThe Doomed Fleet#  \nAccept #ACCEPTLightforge Iron#\n \nTurn in #TURNINThe Missing Diplomat# pt.10 \nAccept #ACCEPTThe Missing Diplomat# pt.11", y = 60.77, x = 10.59, QA = 1249, zone = "Wetlands", QT = 1248},
{ str = "#DOQUEST*# Go outside and defeat Tapoke Jahn", QC = 1249},
{ str = "Turn in #TURNINThe Missing Diplomat# pt.11", y = 60.77, x = 10.59, zone = "Wetlands", QT = 1249},
{ str = "Accept #ACCEPTThe Missing Diplomat# pt.12", y = 60.25, x = 10.54, QA = 1250, zone = "Wetlands"},
{ str = "Turn in #TURNINThe Missing Diplomat# pt.12 \nAccept #ACCEPTThe Missing Diplomat# pt.13", y = 60.77, x = 10.59, QA = 1264, zone = "Wetlands", QT = 1250},
{ str = "Turn in #TURNINLightforge Iron#  \nAccept #ACCEPTThe Lost Ingots#", y = 64.19, x = 12.1, QA = 324, zone = "Wetlands", QT = 321},
{ str = "#DOQUEST*# Kill murlocs", y = 69.7, x = 9.54, zone = "Wetlands", QC = 324},
{ str = "Turn in #TURNINThe Lost Ingots#  \nAccept #ACCEPTBlessed Arm#", y = 60.59, x = 10.58, QA = 322, zone = "Wetlands", QT = 324},
{ str = "Fly to  Southshore", typ = "fly"},
{ str = "As you quest through Hillsbrad pay attention to the syndicate assassin event in southshore  \nIf you manage to kill an assassin, turn in the #ACCEPT*##TURNINAssassin's Contract# and skip the follow up\nFly to Southshore\n \nAccept #ACCEPTCostly Menace#", y = 55.96, x = 52.41, QA = 564, zone = "Hillsbrad Foothills"},
{ str = "Turn in #TURNINSouthshore#", y = 57.09, x = 50.57, zone = "Hillsbrad Foothills", QT = 538},
{ str = "Accept #ACCEPTHints of a New Plague?#", y = 59.04, x = 50.34, QA = 659, zone = "Hillsbrad Foothills"},
{ str = "Accept #ACCEPTDown the Coast#", y = 58.38, x = 51.46, QA = 536, zone = "Hillsbrad Foothills"},
{ str = "Accept #ACCEPTSoothing Turtle Bisque#", y = 58.67, x = 51.88, QA = 555, zone = "Hillsbrad Foothills"},
{ str = "Set your HS to  Southshore", typ = "home"},
{ str = "Do #DOQUESTDown the Coast#", y = 66.57, x = 46.18, zone = "Hillsbrad Foothills", QC = 536},
{ str = "Turn in #TURNINDown the Coast#  \nAccept #ACCEPTFarren's Proof#", y = 58.38, x = 51.46, QA = 559, zone = "Hillsbrad Foothills", QT = 536},
{ str = "Do #DOQUESTFarren's Proof#", y = 72.81, x = 32.04, zone = "Hillsbrad Foothills", QC = 559},
{ str = "Turn in #TURNINFarren's Proof#  \nAccept #ACCEPTFarren's Proof#", y = 58.38, x = 51.46, QA = 560, zone = "Hillsbrad Foothills", QT = 559},
{ str = "Turn in #TURNINFarren's Proof#  \nAccept #ACCEPTFarren's Proof#", y = 58.73, x = 49.47, QA = 561, zone = "Hillsbrad Foothills", QT = 560},
{ str = "Accept #ACCEPTSyndicate Assassins#", y = 59.1, x = 48.13, QA = 505, zone = "Hillsbrad Foothills"},
{ str = "Turn in #TURNINFarren's Proof#  \nAccept #ACCEPTStormwind Ho!#", y = 58.38, x = 51.46, QA = 562, zone = "Hillsbrad Foothills", QT = 561},
{ str = "#DOQUEST*# Kill Nagas", y = 67.82, x = 57.31, zone = "Hillsbrad Foothills", QC = 562},
{ str = "Turn in #TURNINStormwind Ho!#  \nAccept #ACCEPTReassignment#", y = 58.38, x = 51.46, QA = 563, zone = "Hillsbrad Foothills", QT = 562},
{ str = "Buy 4xSoothing Spices", y = 55.06, x = 48.96, zone = "Hillsbrad Foothills"},
{ str = "#DOQUEST*# Loot granite chunks inside the Yeti cave", y = 29.32, x = 43.99, zone = "Hillsbrad Foothills", QC = 689},
{ str = "Do #DOQUESTCostly Menace#", y = 84.58, x = 30.92, zone = "Alterac Mountains", QC = 564},
{ str = "Click on the scroll on top of the table  \nAccept #ACCEPTForeboding Plans#  \nAccept #ACCEPTEncrypted Letter#", y = 67.92, x = 58.31, QA = {510,511}, zone = "Alterac Mountains"},
{ str = "Do #DOQUESTSyndicate Assassins#", y = 67.97, x = 58.3, zone = "Alterac Mountains", QC = 505},
{ str = "#DOQUEST*# Kill turtles along the river", y = 12.4, x = 69.3, zone = "Hillsbrad Foothills", QC = { [555] = 1}},
{ str = "Get the  Western Plaguelands FP", y = 85.06, x = 42.93, zone = "Western Plaguelands", typ = "fp"},
{ str = "Fly to  Southshore", typ = "fly"},
{ str = "Turn in #TURNINEncrypted Letter#  \nAccept #ACCEPTLetter to Stormpike#", y = 57.09, x = 50.57, QA = 514, zone = "Hillsbrad Foothills", QT = 511},
{ str = "Turn in #TURNINSoothing Turtle Bisque#", y = 58.67, x = 51.88, zone = "Hillsbrad Foothills", QT = 555},
{ str = "Turn in #TURNINSyndicate Assassins#  \nTurn in #TURNINForeboding Plans#", y = 59.1, x = 48.13, zone = "Hillsbrad Foothills", QT = {505,510}},
{ str = "Turn in #TURNINCostly Menace#", y = 55.96, x = 52.41, zone = "Hillsbrad Foothills", QT = 564},
{ str = "Fly to  Arathi Highlands", typ = "fly"},
{ str = "Accept #ACCEPTNorthfold Manor#", y = 47.55, x = 45.83, QA = 681, zone = "Arathi Highlands"},
{ str = "Turn in #TURNINMalin's Request#", y = 47.01, x = 46.65, zone = "Arathi Highlands", QT = 690},
{ str = "Turn in #TURNINHints of a New Plague?#  \nAccept #ACCEPTHints of a New Plague?#", y = 53.84, x = 60.18, QA = 658, zone = "Arathi Highlands", QT = 659},
{ str = "#DOQUEST*# Use eagle eye to find the Forsaken Courier \nIf the courier is not in Arathi, look for it in Hillsbrad after finishing Northfold Manor\n \nDo #DOQUESTNorthfold Manor#", y = 30.13, x = 33.25, zone = "Arathi Highlands", QC = 681, unitscan = "FORSAKEN COURIER"},
{ str = "Hearth back to  Southshore\n \nStable your pet "},
{ str = "Fly to  Arathi Highlands", typ = "fly"},
{ str = "Turn in #TURNINNorthfold Manor#", y = 47.55, x = 45.83, zone = "Arathi Highlands", QT = 681},
{ str = "Use eagle eye to find a level 32/33 spider  \nTame it and learn Bite rank 5 \n \nTurn in #TURNINHints of a New Plague?#  \nDon't go out of your way to find the courier, you can skip this step and finish it later", y = 53.84, x = 60.18, zone = "Arathi Highlands", QT = 658},
{ str = "Fly to  Wetlands", typ = "fly"},
        }
    },

-----------27-28 Lakeshire
    --[207] = {
    [2728] = {
        title = "33-34 Shimmering Flats",
        --n = "27-28 Lakeshire",
        --pID = 206, nID = 208,
        --itemCount = 18,
        items = {



{ str = "Take the boat to Theramore \n \nGet the  Theramore FP", y = 51.3, x = 67.47, zone = "Dustwallow Marsh", typ = "fp"},
{ str = "Withdraw your main pet from the stables \n \nAccept #ACCEPTThey Call Him Smiling Jim#", y = 46.06, x = 66.15, QA = 1282, zone = "Dustwallow Marsh"},
{ str = "Accept #ACCEPTHighperch Venom#", y = 45.14, x = 66.45, QA = 1135, zone = "Dustwallow Marsh"},
{ str = "Set your HS to  Theramore", typ = "home"},
{ str = "Speak with Clerk Lendry \nTurn in #TURNINJames Hyal#", y = 48.24, x = 67.87, zone = "Dustwallow Marsh", QT = 1302},
{ str = "Turn in #TURNINThe Missing Diplomat#  \nAccept #ACCEPTThe Missing Diplomat#  \nTurn in #TURNINThey Call Him Smiling Jim#", y = 48.7, x = 68.02, QA = 1265, zone = "Dustwallow Marsh", QT = {1264,1282}},
{ str = "Make sure you have 3xSoothing Spices\n \n#DOQUEST*# Head to Sentry Point", y = 41.17, x = 59.71, zone = "Dustwallow Marsh", QC = 1265},
{ str = "Turn in #TURNINThe Missing Diplomat#  \nAccept #ACCEPTThe Missing Diplomat#", y = 49.26, x = 66.42, QA = 1266, zone = "Dustwallow Marsh", QT = 1265},
{ str = "Accept #ACCEPTSoothing Spices#  \nTurn in #TURNINSoothing Spices#", y = 26.26, x = 55.43, QA = 1218, zone = "Dustwallow Marsh", QT = 1218},
{ str = "Click the dirt mound and accept #ACCEPTThe Orc Report#", y = 25.92, x = 55.44, QA = 1219, zone = "Dustwallow Marsh"},
{ str = "Turn in #TURNINThe Missing Diplomat#  \nAccept #ACCEPTThe Missing Diplomat#", y = 24.64, x = 45.22, QA = 1324, zone = "Dustwallow Marsh", QT = 1266},
{ str = "#DOQUESTBeat Private Hendel#  \nTurn in #TURNINThe Missing Diplomat#", y = 49.26, x = 66.42, zone = "Dustwallow Marsh", QC = 1324, QT = 1324},
{ str = "Speak with Jaina \nAccept #ACCEPTThe Missing Diplomat#  \nTurn in #TURNINThe Missing Diplomat#", y = 49.03, x = 66.26, QA = 1267, zone = "Dustwallow Marsh", QT = 1267},
{ str = "Accept #ACCEPTHungry!#", y = 38.25, x = 35.15, QA = 1177, zone = "Dustwallow Marsh"},
{ str = "Click on the badge on top of a wooden plank, on the black shield hanging on top of the fireplace and on the hoofprint right outside the inn\n \nAccept #ACCEPTSuspicious Hoofprints#  \nAccept #ACCEPTThe Black Shield#  \nAccept #ACCEPTLieutenant Paval Reethe#", y = 47.63, x = 29.69, QA = {1284,1252,1253}, zone = "Dustwallow Marsh"},
{ str = "Run to Thousand Needles  \nClick on the book next to the dead dwarf  \nAccept #ACCEPTLonebrow's Journal#", y = 24.34, x = 30.71, QA = 1100, zone = "Thousand Needles"},
{ str = " Get the  Thalanaar FP", y = 17.87, x = 7.84, zone = "Thousand Needles", typ = "fp"},
{ str = "Turn in #TURNINLonebrow's Journal# ", y = 19, x = 8.05, zone = "Thousand Needles", QT = 1100},
{ str = "Do #DOQUESTHighperch Venom#", y = 42.01, x = 17.28, zone = "Thousand Needles", QC = 1135},
{ str = "Talk to Kravel Koalbeard \nAccept #ACCEPTRocket Car Parts#  \nSkip the other 2 quests from this quest giver", y = 77.26, x = 77.78, QA = 1110, zone = "Thousand Needles"},
{ str = "Talk with the gnome brothers \nAccept #ACCEPTSalt Flat Venom#  \nTurn in #TURNINThe Brassbolts Brothers#  \nAccept #ACCEPTHardened Shells#", y = 77.12, x = 78.06, QA = {1104,1105}, zone = "Thousand Needles", QT = 1179},
{ str = "Accept #ACCEPTLoad Lightening#", y = 75.88, x = 80.17, QA = 1176, zone = "Thousand Needles"},
{ str = "Accept #ACCEPTA Bump in the Road#", y = 77.95, x = 81.63, QA = 1175, zone = "Thousand Needles"},
{ str = "#DOQUEST*# Kill basilisks as you go around\n \n#DOQUEST*##DOQUEST*##DOQUEST*##DOQUEST*# Run counter clockwise around the race track until you complete all quests, make sure to prioritize vultures/scorpids", y = 65.48, x = 87.5, zone = "Thousand Needles", QC = { [1104] = 0, [1105] = 0, [1176] = 0, [1110] = 0}},
{ str = "Turn in #TURNINA Bump in the Road#", y = 77.95, x = 81.63, zone = "Thousand Needles", QT = 1175},
{ str = "Turn in #TURNINLoad Lightening#  \nAccept #ACCEPTGoblin Sponsorship#", y = 75.88, x = 80.17, QA = 1178, zone = "Thousand Needles", QT = 1176},
{ str = "Turn in #TURNINHardened Shells#  \nTurn in #TURNINSalt Flat Venom#", y = 77.12, x = 78.14, zone = "Thousand Needles", QT = {1105,1104}},
{ str = "Turn in #TURNINRocket Car Parts#  \nAccept #ACCEPTWharfmaster Dizzywig#  \nAccept #ACCEPTHemet Nesingwary#", y = 77.26, x = 77.78, QA = {1111,5762}, zone = "Thousand Needles", QT = 1110},
{ str = " Get the  Tanaris FP", y = 29.35, x = 51.01, zone = "Tanaris", typ = "fp"},
{ str = "Hearth to  Theramore\n \nTurn in #TURNINHighperch Venom#", y = 45.14, x = 66.45, zone = "Dustwallow Marsh", QT = 1135},
{ str = "Turn in #TURNINThe Orc Report#  \nAccept #ACCEPTCaptain Vimes#", y = 50.41, x = 68.13, QA = 1220, zone = "Dustwallow Marsh", QT = 1219},
{ str = "Turn in #TURNINCaptain Vimes#  \nTurn in #TURNINLieutenant Paval Reethe#  \nAccept #ACCEPTLieutenant Paval Reethe#  \nTurn in #TURNINThe Black Shield#  \nAccept #ACCEPTThe Black Shield#  \nTurn in #TURNINSuspicious Hoofprints#", y = 48.62, x = 68.21, QA = {1259,1319}, zone = "Dustwallow Marsh", QT = {1284,1252,1220,1253}},
{ str = "Turn in #TURNINLieutenant Paval Reethe#  \nAccept #ACCEPTDaelin's Men#", y = 48.11, x = 68.04, QA = 1285, zone = "Dustwallow Marsh", QT = 1259},
{ str = "Turn in #TURNINDaelin's Men#", y = 48.62, x = 68.21, zone = "Dustwallow Marsh", QT = 1285},
{ str = "Turn in #TURNINThe Black Shield#  \nAccept #ACCEPTThe Black Shield#", y = 50.42, x = 64.75, QA = 1320, zone = "Dustwallow Marsh", QT = 1319},
{ str = "Turn in #TURNINThe Black Shield#", y = 48.62, x = 68.21, zone = "Dustwallow Marsh", QT = 1320},
{ str = "Grind your way northwest towards Ratchet", y = 14.42, x = 51.71, zone = "Dustwallow Marsh"},
{ str = "Unstuck to Ratchet once you get to The Barrens\n \nGet the  Ratchet FP", y = 37.16, x = 63.08, zone = "The Barrens", typ = "fp"},
{ str = "Turn in #TURNINGoblin Sponsorship#  \nAccept #ACCEPTGoblin Sponsorship#", y = 36.23, x = 62.68, QA = 1180, zone = "The Barrens", QT = 1178},
{ str = "Turn in #TURNINWharfmaster Dizzywig#  \nAccept #ACCEPTParts for Kravel#", y = 38.45, x = 63.35, QA = 1112, zone = "The Barrens", QT = 1111},
{ str = "Deposit the following items: \nFarren's Report \nCleverly Encrypted Letter \nAlterac Granite \nMirefin Head \n \nTake the Boat to Booty Bay"},
        }
    },

-----------28-29 Duskwood
    --[208] = {
    [2829] = {
        title = "34-35 STV part 1",
		--minlevel = 34
		--maxlevel = 35
        --n = "28-29 Duskwood",
        --pID = 207, nID = 209,
        --itemCount = 48,
        items = {
            

{ str = "Deposit the following items: \nFarren's Report \nCleverly Encrypted Letter \nAlterac Granite \nMirefin Head \n \nTurn in #TURNINGoblin Sponsorship#  \nAccept #ACCEPTGoblin Sponsorship#", y = 73.56, x = 26.34, QA = 1181, zone = "Stranglethorn Vale", QT = 1180},
{ str = "Enter the inn from the bottom floor  \nAccept #ACCEPTSinging Blue Shards#", y = 77.2, x = 27.11, QA = 605, zone = "Stranglethorn Vale"},
{ str = " Set your HS to Booty Bay", typ = "home"},
{ str = "Speak to Kebok \nAccept #ACCEPTHostile Takeover#  \n  \nSpeak to Krazek \nAccept #ACCEPTSupplies to Private Thorsen#  \nAccept #ACCEPTInvestigate the Camp#  \nAccept #ACCEPTThe Haunted Isle#", y = 77.11, x = 26.98, QA = {198,616,201,213}, zone = "Stranglethorn Vale"},
{ str = "Talk to Baron Revilgaz \nTurn in #TURNINThe Haunted Isle#  \nAccept #ACCEPTThe Stone of the Tides#  \nTurn in #TURNINGoblin Sponsorship#  \nAccept #ACCEPTGoblin Sponsorship#", y = 76.87, x = 27.22, QA = {578,1182}, zone = "Stranglethorn Vale", QT = {616,1181}},
{ str = "Accept #ACCEPTSupply and Demand#", y = 77.59, x = 28.29, QA = 575, zone = "Stranglethorn Vale"},
{ str = "Throw away the Library Scrip\n \nFly to  Westfall", typ = "fly"},
{ str = "Turn in #TURNINA Daughter's Love#", y = 29.07, x = 17.72, zone = "Duskwood", QT = 231},
{ str = "Turn in #TURNINSupplies to Private Thorsen#\nTurn in #ACCEPT*##TURNINJungle Secrets# if you have it, otherwise keep an eye for Private Thorsen's RP sequence \nHe patrols down the road every 30 minutes\n \nRun to the STV/Duskwood border \nAccept #ACCEPTThe Second Rebellion#  \nAccept #ACCEPTBad Medicine#", y = 88.53, x = 38.45, QA = {203,204}, zone = "Duskwood"},
{ str = "#DOQUEST*#Kill basilisks \n#DOQUEST*#Kill river crocolisks \n \nHead to STV \nAccept #ACCEPTWelcome to the Jungle#  \nTurn in #TURNINWelcome to the Jungle#", y = 10.52, x = 35.66, QA = 583, zone = "Stranglethorn Vale", QT = 583},
{ str = "Accept #ACCEPTTiger Mastery# pt.1 \nAccept #ACCEPTPanther Mastery# pt.1", y = 10.61, x = 35.61, QA = {185,190}, zone = "Stranglethorn Vale"},
{ str = "Turn in #TURNINHemet Nesingwary#\nDo #DOQUESTTiger Mastery#\n \nTurn in #TURNINTiger Mastery# pt.1 \nAccept #ACCEPTTiger Mastery# pt.2", y = 10.61, x = 35.61, QA = 186, zone = "Stranglethorn Vale", QT = 185},
{ str = "#DOQUEST*##DOQUEST*# Do the Kurzen compound quests", y = 10.25, x = 44.93, zone = "Stranglethorn Vale", QC = { [203] = 0, [204] = 0}},
{ str = "#DOQUEST*# Kill tigers, look for basilisks northeast", y = 15.81, x = 46.75, zone = "Stranglethorn Vale", QC = 186},
{ str = "#DOQUEST*#Get the key from a named mob on top of the oil rig  \nOpen the chest inside the house next to the lumber mill", y = 18.38, x = 45.52, zone = "Stranglethorn Vale", QC = 1182},
{ str = "#DOQUEST*# Kill geologists", y = 20.23, x = 45.48, zone = "Stranglethorn Vale", QC = 213},
{ str = "Finish off #DOQUESTPanther Mastery#", y = 12.49, x = 41.89, zone = "Stranglethorn Vale", QC = 190},
{ str = "Accept #ACCEPTKrazek's Cookery#", y = 3.3, x = 37.7, QA = 210, zone = "Stranglethorn Vale"},
{ str = "Turn in #TURNINThe Second Rebellion#  \nTurn in #TURNINBad Medicine#", y = 3.32, x = 38.01, zone = "Stranglethorn Vale", QT = {203,204}},
{ str = "Turn in #TURNINPanther Mastery# pt.1\n \nTurn in #TURNINTiger Mastery#  \nAccept #ACCEPTTiger Mastery#  \nTurn in #TURNINHemet Nesingwary#  \nAccept #ACCEPTRaptor Mastery#  \nAccept #ACCEPTPanther Mastery#", y = 10.61, x = 35.61, QA = {194,187,191}, zone = "Stranglethorn Vale", QT = {186,5762}},
{ str = "Finish off #DOQUESTSupply and Demand#", y = 9.16, x = 35.22, zone = "Stranglethorn Vale", QC = 575},
{ str = "Do #DOQUESTPanther Mastery#  \nDo #DOQUESTTiger Mastery#", y = 11.01, x = 29.4, zone = "Stranglethorn Vale", QC = { [191] = 0, [187] = 0}},
{ str = "Do #DOQUESTRaptor Mastery#", y = 16.31, x = 26.87, zone = "Stranglethorn Vale", QC = 194},
{ str = "#DOQUEST*#Finish off basilisks", y = 17.88, x = 25.55, zone = "Stranglethorn Vale", QC = 605},
{ str = "#DOQUEST*#Once all objectives are complete, head to the island west", y = 22.69, x = 20.7, zone = "Stranglethorn Vale", QC = 578},
{ str = "Kill yourself, spirit rez \n \nTurn in #TURNINTiger Mastery#  \nAccept #ACCEPTTiger Mastery#  \nTurn in #TURNINPanther Mastery#  \nAccept #ACCEPTPanther Mastery#  \nTurn in #TURNINRaptor Mastery#  \nAccept #ACCEPTRaptor Mastery#", y = 10.61, x = 35.61, QA = {192,188,195}, zone = "Stranglethorn Vale", QT = {191,187,194}},
{ str = " Hearth to Booty Bay\n \nTurn in #TURNINSinging Blue Shards#", y = 77.2, x = 27.11, zone = "Stranglethorn Vale", QT = 605},
{ str = "Turn in #TURNINInvestigate the Camp#  \nTurn in #TURNINKrazek's Cookery#", y = 77.2, x = 26.94, zone = "Stranglethorn Vale", QT = {201,210}},
{ str = "Turn in #TURNINHostile Takeover#  \nAccept #ACCEPTBloodscalp Ears#", y = 77.11, x = 26.98, QA = 189, zone = "Stranglethorn Vale", QT = 213},
{ str = "Turn in #TURNINGoblin Sponsorship#  \nAccept #ACCEPTGoblin Sponsorship#  \nTurn in #TURNINThe Stone of the Tides#  \nAccept #ACCEPTWater Elementals#", y = 76.87, x = 27.22, QA = {1183,601}, zone = "Stranglethorn Vale", QT = {1182,578}},
{ str = "Turn in #TURNINSupply and Demand#  \nAccept #ACCEPTSome Assembly Required#", y = 77.59, x = 28.29, QA = 577, zone = "Stranglethorn Vale", QT = 575},
{ str = "Fly to  Stormwind", typ = "fly"},
{ str = "Withdraw the following items: \nFarren's Report \nCleverly Encrypted Letter \nAlterac Granite \nWater Breathing Potions \n \nTurn in #TURNINReassignment#", y = 15.84, x = 72.6, zone = "Stormwind City", QT = 563},
{ str = "Skip this step if you haven't found the quest item \nTurn in #ACCEPT*##TURNINAn Old History Book#  \nAccept #ACCEPTSouthshore#", y = 7.48, x = 74.15, QA = {337,538}, zone = "Stormwind City", QT = 337},
{ str = "Turn in #TURNINBlessed Arm#  \nAccept #ACCEPTArmed and Ready#", y = 12.06, x = 51.75, QA = 325, zone = "Stormwind City", QT = 322},
{ str = "Take the tram to Ironforge \n \nAccept #ACCEPTReclaimers' Business in Desolace#", y = 17.49, x = 67.9, QA = 1453, zone = "Ironforge"},
{ str = "Turn in #TURNINLetter to Stormpike#  \nAccept #ACCEPTFurther Mysteries#", y = 11.74, x = 74.64, QA = 525, zone = "Ironforge", QT = 514},
{ str = "Turn in #TURNINA King's Tribute#  \nWait for the RP sequence to end  \nAccept #ACCEPTA King's Tribute#", y = 88.04, x = 39.03, QA = 700, zone = "Ironforge", QT = 689},
{ str = "Withdraw water breathing pots from your bank \n \nTurn in #TURNINA King's Tribute#", y = 56.19, x = 39.09, zone = "Ironforge", QT = 700},
{ str = "Fly to  Wetlands", typ = "fly"},
        }
    },

-----------29-30 Ashenvale
    --[209] = {
    [2930] = {
        title = "35-37 Desolace",
		--minlevel = 35
		--maxlevel = 37
        --n = "29-30 Ashenvale",
        --pID = 208, nID = 210,
        --itemCount = 18,
        items = {
 



{ str = "Make sure you accepted #ACCEPTReclaimers' Business in Desolace# in Ironforge\n \nTake the boat to Darkshore"},
{ str = "Fly to  Stonetalon", typ = "fly"},
{ str = "Head to Desolace \nFly to Desolace if you have the FP\n \nAccept #ACCEPTVahlarriel's Search#", y = 11.81, x = 66.4, QA = 1437, zone = "Desolace"},
{ str = "Get the  Desolace FP", y = 10.53, x = 64.65, zone = "Desolace", typ = "fp"},
{ str = "Set your HS to  Nijel's Point", y = 6.55, x = 66.28, zone = "Desolace", typ = "home"},
{ str = "Turn in #TURNINReclaimers' Business in Desolace#  \nAccept #ACCEPTThe Karnitol Shipwreck#  \nAccept #ACCEPTReagents for Reclaimers Inc.# ", y = 9.62, x = 66.2, QA = {1454,1458}, zone = "Desolace", QT = 1453},
{ str = "Accept #ACCEPTCentaur Bounty#  \nAccept #ACCEPTStrange Alliance#", y = 10.87, x = 66.74, QA = {1387,1382}, zone = "Desolace"},
{ str = "#DOQUEST*#Kill Satyrs", y = 22.55, x = 78.06, zone = "Desolace", QC = 1458},
{ str = "Turn in #TURNINReagents for Reclaimers Inc.#  \nAccept #ACCEPTReagents for Reclaimers Inc.#", y = 9.62, x = 66.2, QA = 1459, zone = "Desolace", QT = 1458},
{ str = "#DOQUEST*# Kill scorpids/aged kodos as you quest \n \nTurn in #TURNINVahlarriel's Search#  \nAccept #ACCEPTVahlarriel's Search#", y = 17.84, x = 56.52, QA = 1465, zone = "Desolace", QT = 1437},
{ str = "Accept #ACCEPTSceptre of Light#", y = 27.16, x = 38.88, QA = 5741, zone = "Desolace"},
{ str = "Click on the small chest on the ground  \nTurn in #TURNINThe Karnitol Shipwreck#  \nAccept #ACCEPTThe Karnitol Shipwreck#", y = 30.45, x = 36.11, QA = 1455, zone = "Desolace", QT = 1454},
{ str = "Click on the small book on the ground next to the chest  \nAccept #ACCEPTClaim Rackmore's Treasure!#", y = 30.4, x = 36.06, QA = 6161, zone = "Desolace"},
{ str = "#DOQUEST*#Murder some crab people", y = 29.8, x = 33.1, zone = "Desolace", QC = { [6161] = 1}},
{ str = "Grind until your HS is off cooldown \nHearth back to Nijel's Point \n \nTurn in #TURNINThe Karnitol Shipwreck#  \nAccept #ACCEPTThe Karnitol Shipwreck#", y = 9.62, x = 66.2, QA = 1456, zone = "Desolace", QT = 1455},
{ str = "Turn in #TURNINVahlarriel's Search#  \nAccept #ACCEPTVahlarriel's Search#", y = 11.81, x = 66.44, QA = 1438, zone = "Desolace", QT = 1465},
{ str = "#DOQUEST*#Climb the tower, kill a Burning Blade Seer ", y = 30.14, x = 55.16, zone = "Desolace", QC = 5741},
{ str = "Turn in #TURNINVahlarriel's Search#  \nAccept #ACCEPTSearch for Tyranis#", y = 26.12, x = 54.85, QA = 1439, zone = "Desolace", QT = 1438},
{ str = "Do #DOQUESTSearch for Tyranis#", y = 29.07, x = 53, zone = "Desolace", QC = 1439},
{ str = "Turn in #TURNINSearch for Tyranis# ", y = 26.12, x = 54.85, zone = "Desolace", QT = 1439},
{ str = "Accept the escort quest #ACCEPTReturn to Vahlarriel#", y = 26.12, x = 54.85, QA = 1440, zone = "Desolace"},
{ str = "#DOQUEST*# Escort Dalinda Malem", QC = 1440},
{ str = "Accept #ACCEPTBone Collector#", y = 38.98, x = 62.32, QA = 5501, zone = "Desolace"},
{ str = "Accept #ACCEPTKodo Roundup#", y = 61.86, x = 60.86, QA = 5561, zone = "Desolace"},
{ str = "#DOQUEST*#Kill centaurs\n \n#DOQUEST*#Keep killing centaurs until you get friendly rep. with Gelkis centaur", y = 76, x = 72, zone = "Desolace", QC = 1382},
{ str = "Do #TURNINKodo Roundup#  \nGrind mobs on your way back and forth \nBe on the lookout for the kodos that patrol next to the quest giver\n \nDo #DOQUESTBone Collector#", y = 58.56, x = 52.5, zone = "Desolace", QC = 5501},
{ str = "Turn in #TURNINKodo Roundup#", y = 61.86, x = 60.86, zone = "Desolace", QT = 5561},
{ str = "Finish off #DOQUESTReagents for Reclaimers Inc.#", y = 33.92, x = 70.14, zone = "Desolace", QC = 1459},
{ str = "Turn in #TURNINBone Collector#", y = 38.98, x = 62.32, zone = "Desolace", QT = 5501},
{ str = "Turn in #TURNINSceptre of Light#  \nAccept #ACCEPTBook of the Ancients#", y = 27.16, x = 38.88, QA = 6027, zone = "Desolace", QT = 5741},
{ str = "#DOQUEST*# Kill nagas \n#DOQUEST*# Kill Sea Witches/Tidehunters \n \n#DOQUEST*# Click on the naga statue", y = 6.57, x = 28.25, zone = "Desolace", QC = 6027},
{ str = "Turn in #TURNINClaim Rackmore's Treasure!#", y = 8.7, x = 30, zone = "Desolace", QT = 6161},
{ str = "Finish off #DOQUESTThe Karnitol Shipwreck#", y = 10.81, x = 28.29, zone = "Desolace", QC = 1456},
{ str = "Turn in #TURNINBook of the Ancients#", y = 27.16, x = 38.88, zone = "Desolace", QT = 6027},
{ str = "Keep grinding mobs until your HS is off cooldown \n Hearth back to Nijel's Point\n \nTurn in #TURNINThe Karnitol Shipwreck#  \nAccept #ACCEPTThe Karnitol Shipwreck#  \nTurn in #TURNINReagents for Reclaimers Inc.#", y = 9.62, x = 66.2, QA = 1457, zone = "Desolace", QT = {1456,1459}},
{ str = "Turn in #TURNINCentaur Bounty#", y = 10.87, x = 66.74, zone = "Desolace", QT = 1387},
{ str = "Turn in #TURNINReturn to Vahlarriel#", y = 11.81, x = 66.44, zone = "Desolace", QT = 1440},
{ str = "Stable your pet \nUnstuck and spirit rez at the kodo graveyard \nTame a Scorpashi Lasher  \nLearn claw rank 5\n \nTurn in #TURNINStrange Alliance#", y = 79.24, x = 36.21, zone = "Desolace", QT = 1382},
{ str = "Head to Feralas", y = 91.72, x = 41.13, zone = "Desolace"},
{ str = "Once you get to feralas, unstuck and rez at the Dire Maul GY\n \nRun to the edge of the dock and unstuck  \nSpirit rez at Feathermoon", y = 42.77, x = 43.33, zone = "Feralas"},
{ str = "Fly to  Tanaris", typ = "fly"},
{ str = "Run to Thousand Needles  \nTurn in #TURNINParts for Kravel#", y = 77.26, x = 77.78, zone = "Thousand Needles", QT = 1112},
{ str = "Accept #ACCEPTEncrusted Tail Fins#", y = 77.12, x = 78.14, QA = 1107, zone = "Thousand Needles"},
{ str = "Turn in #TURNINGoblin Sponsorship#  \nAccept #ACCEPTThe Eighteenth Pilot#", y = 75.88, x = 80.17, QA = 1186, zone = "Thousand Needles", QT = 1183},
{ str = "Turn in #TURNINThe Eighteenth Pilot#  \nAccept #ACCEPTRazzeric's Tweaking#", y = 76.09, x = 80.32, QA = 1187, zone = "Thousand Needles", QT = 1186},
{ str = "Accept #ACCEPTDelivery to the Gnomes#", y = 77.26, x = 77.78, QA = 1114, zone = "Thousand Needles"},
{ str = "Turn in #TURNINDelivery to the Gnomes#", y = 77.12, x = 78.06, zone = "Thousand Needles", QT = 1114},
{ str = "Accept #ACCEPTThe Rumormonger#", y = 77.26, x = 77.78, QA = 1115, zone = "Thousand Needles"},
{ str = "You have 2 options going into the next segment: \nFly to  Ratchet and take the boat to Booty Bay \nOR \nYou can use the unstuck self service through the battle.net website and teleport to SW", typ = "fly"},
        }
    },

-----------30-30 Wetlands
    --[210] = {
    [3030] = {
        title = "37-38 STV part 2",
		--minlevel = 37
		--maxlevel = 38
        --n = "30-30 Wetlands",
        --pID = 209, nID = 301,
        --itemCount = 18,
        items = {


{ str = "Withdraw Small Brass Key \nWithdraw water breathing pots \n \nDeposit the following items: \nKarnitol's Satchel \nDecrypted Letter \nLetter of Commendation \nFizzle Brassbolts' Letter \nBuzzard Wing "},
{ str = "Set your HS to Booty Bay", typ = "home"},
{ str = "Turn in #TURNINThe Rumormonger#\n \nAccept #ACCEPTBloodscalp Ears#  \nAccept #ACCEPTWater Elementals#  \nAccept #ACCEPTSome Assembly Required# ", y = 77.12, x = 26.99, QA = {189,601,577}, zone = "Stranglethorn Vale"},
{ str = "Fly to Westfall", typ = "fly"},
{ str = "Run to STV \nAccept #ACCEPTBookie Herod#\n \nAccept #ACCEPTSpecial Forces#  \nAccept #ACCEPTKurzen's Mystery#", y = 3.32, x = 38.01, QA = {574,207}, zone = "Stranglethorn Vale"},
{ str = "Accept #ACCEPTPanther Mastery#  \nAccept #ACCEPTRaptor Mastery#  \nAccept #ACCEPTTiger Mastery#", y = 10.54, x = 35.55, QA = {195,188,192}, zone = "Stranglethorn Vale"},
{ str = "Click on the pile of books upstairs  \nTurn in #TURNINBookie Herod#  \nAccept #ACCEPTThe Hidden Key#", y = 9.37, x = 43.67, QA = 328, zone = "Stranglethorn Vale", QT = 200},
{ str = "Turn in #TURNINThe Hidden Key#  \nAccept #ACCEPTThe Spy Revealed!#", y = 7.56, x = 49.61, QA = 329, zone = "Stranglethorn Vale", QT = 328},
{ str = "Finish off #DOQUESTSpecial Forces#", y = 7.47, x = 47.05, zone = "Stranglethorn Vale", QC = 574},
{ str = "Do #DOQUESTPanther Mastery#", y = 22.95, x = 48.64, zone = "Stranglethorn Vale", QC = 192},
{ str = "#DOQUEST*#Look for crocs along the river bank\n \nDo #DOQUESTRaptor Mastery#", y = 20.49, x = 38.1, zone = "Stranglethorn Vale", QC = 195},
{ str = "Finish off #DOQUESTSome Assembly Required#", y = 16.64, x = 41.13, zone = "Stranglethorn Vale", QC = 577},
{ str = "Do #DOQUESTTiger Mastery#", y = 17.38, x = 32.21, zone = "Stranglethorn Vale", QC = 188},
{ str = "Collect #DOQUESTBloodscalp Ears# as you go around\n \n#DOQUEST*#Loot the first tablet", y = 19.14, x = 29.48, zone = "Stranglethorn Vale", QC = { [207] = 1}},
{ str = "#DOQUEST*#Loot the fourth tablet", y = 8.92, x = 24.69, zone = "Stranglethorn Vale", QC = { [207] = 8}},
{ str = "#DOQUEST*#Loot the third tablet", y = 12.01, x = 22.94, zone = "Stranglethorn Vale", QC = { [207] = 4}},
{ str = "Finish off #DOQUESTBloodscalp Ears#", y = 9.6, x = 25.2, zone = "Stranglethorn Vale", QC = 189},
{ str = "Grind until you are 30k xp off level 38"},
{ str = "Do #DOQUESTWater Elementals#", y = 23.51, x = 21.55, zone = "Stranglethorn Vale", QC = 601},
{ str = "#DOQUEST*#Loot the second tablet underwater", y = 23.02, x = 24.82, zone = "Stranglethorn Vale", QC = { [207] = 2}},
{ str = "Collect 9 Blue Pearls from the clams around the coral reef\n \nKill Murlocs for #DOQUEST*#Encrusted Tail Fins", y = 24.46, x = 24.42, zone = "Stranglethorn Vale", QC = 1107},
{ str = "Grind until you are 18,600 xp away from level 38"},
{ str = "Kill yourself, spirit rez \n \nTurn in #TURNINKurzen's Mystery#  \nAccept #ACCEPTTroll Witchery#", y = 3.56, x = 37.83, QA = 205, zone = "Stranglethorn Vale", QT = 207},
{ str = "Turn in #TURNINThe Spy Revealed!#  \nAccept #ACCEPTPatrol Schedules#", y = 3.01, x = 38.04, QA = 330, zone = "Stranglethorn Vale", QT = 329},
{ str = "Turn in #TURNINSpecial Forces#  \nAccept #ACCEPTColonel Kurzen#", y = 3.01, x = 38.04, QA = 202, zone = "Stranglethorn Vale", QT = 574},
{ str = "Turn in #TURNINPatrol Schedules#  \nAccept #ACCEPTReport to Doren#", y = 3.39, x = 37.66, QA = 331, zone = "Stranglethorn Vale", QT = 330},
{ str = "Turn in #TURNINReport to Doren#", y = 3.01, x = 38.04, zone = "Stranglethorn Vale", QT = 331},
{ str = "Turn in #TURNINTiger Mastery#  \nTurn in #TURNINRaptor Mastery#  \nAccept #ACCEPTRaptor Mastery#  \nTurn in #TURNINPanther Mastery#  \nAccept #ACCEPTPanther Mastery#", y = 10.61, x = 35.61, QA = {196,193}, zone = "Stranglethorn Vale", QT = {195,188,192}},
{ str = "Use your Hearthstone\n \nHead to Booty Bay \nTurn in #TURNINThe Rumormonger#  \nAccept #ACCEPTDream Dust in the Swamp#  \nTurn in #TURNINBloodscalp Ears#", y = 77.2, x = 26.94, QA = 1116, zone = "Stranglethorn Vale", QT = {1115,189}},
{ str = "Turn in #TURNINWater Elementals#  \nAccept #ACCEPTMagical Analysis#", y = 76.87, x = 27.22, QA = 602, zone = "Stranglethorn Vale", QT = 601},
{ str = "Set your HS to  Booty Bay if you haven't", typ = "home"},
{ str = "Turn in #TURNINSome Assembly Required#", y = 77.59, x = 28.29, zone = "Stranglethorn Vale", QT = 577},
{ str = "Make sure you are level 38 before starting the next segment"},
{ str = "Fly to  Stormwind", typ = "fly"},


        }
    },
}