--[[--------------------------------------------------
003_Alliance_40to50.lua
Authors: mrmr
Version: 1.04.2
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 40 to Lvl 50
    1.04.1
        -- First Release
            Alliance's Guide
            from level 40 to lever 50
    1.04.2
    	-- no changes in here for this revision
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Alliance_40to50 = {
-----------40-41 Badlands
	--[401] = {
	[4041] = {
		title = "51-51 Blasted Lands",
		--n = "40-41 Badlands",
		--pID = 312, nID = 402,
		--itemCount = 32,
		items = {
{ str = "Climb the tower and accept #ACCEPTPetty Squabbles#", y = 19.29, x = 67.56, QA = 2783, zone = "Blasted Lands"},
{ str = "Turn in #TURNINPetty Squabbles#  \nAccept #ACCEPTA Tale of Sorrow# ", y = 2.94, x = 52.76, QA = 2801, zone = "Blasted Lands", QT = 2783},
{ str = "#DOQUEST*#Go through his whole dialogue.\n \nTurn in #TURNINA Tale of Sorrow#", y = 2.93, x = 52.76, zone = "Blasted Lands", QT = 2801},
{ str = "Turn in #ACCEPT*##TURNINEverything Counts In Large Amounts# if you find an Imperfect Draenethyst Fragment\n \nTurn in #ACCEPT*##TURNINThe Decisive Striker# once you have: \n3 Scorpok Pincer \n2 Vulture Gizzard \n1 Blasted Boar Lung", y = 14.2, x = 50.55, QA = 2585, zone = "Blasted Lands", QT = 2585},
{ str = "Collect the following items: \n    12 Vulture Gizzard \n    11 Basilisk Brain \n    3 Scorpok Pincer \n    5 Blasted Boar Lung \n    5 Snickerfang Jowl \n \nTurn in #ACCEPT*##TURNINA Boar's Vitality#  \nTurn in #ACCEPT*##TURNINSnickerfang Jowls#  \nTurn in #ACCEPT*##TURNINThe Basilisk's Bite#  \nTurn in #ACCEPT*##TURNINVulture's Vigor#", y = 14.2, x = 50.55, QA = {2581,2583,2603,2601}, zone = "Blasted Lands", QT = {2581,2583,2603,2601}},
{ str = "Fly to  Redridige", typ = "fly"},
{ str = "Head to Burning Steppes \nAccept #ACCEPTExtinguish the Firegut#", y = 68.67, x = 84.55, QA = 3823, zone = "Burning Steppes"},
{ str = "Do #DOQUESTExtinguish the Firegut#", y = 44.38, x = 80.74, zone = "Burning Steppes", QC = 3823},
{ str = "Turn in #TURNINExtinguish the Firegut#", y = 68.67, x = 84.55, zone = "Burning Steppes", QT = 3823},
{ str = "Fly to  Ironforge", typ = "fly"},
		}
	},

-----------41-41 Swamp of Sorrows
	--[402] = {
	[4141] = {
		title = "51-52 Western Plaguelands",
		--n = "41-41 Swamp of Sorrows",
		--pID = 401, nID = 403,
		--itemCount = 27,
		items = {


{ str = "Withdraw the following items from your bank: \nSuper Snapper FX \nSnapshot of Gammerita \nWildkin Feather"},
{ str = "Do the Gnomeregan cloth turn ins: \n#ACCEPT*##TURNINWool#, #ACCEPT*##TURNINSilk#, #ACCEPT*##TURNINMageweave#\nDo the Ironforge cloth turn ins: \n#ACCEPT*##TURNINWool#, #ACCEPT*##TURNINSilk#, #ACCEPT*##TURNINMageweave#\n \nAccept #ACCEPTA Call to Arms: The Plaguelands!#", y = 81.39, x = 55.91, QA = 5090, zone = "Ironforge", unitscan = "COURIER HAMMERFALL"},
{ str = "Accept #ACCEPTA Little Slime Goes a Long Way# \nTurn in #TURNINProof of Deed#  \nAccept #ACCEPTAt Last!# \nTurn in #TURNINSuntara Stones#", y = 23.38, x = 75.76, QA = {4512,3201}, zone = "Ironforge", QT = {3182,3368}},
{ str = "Accept #ACCEPTPassing the Burden#", y = 11.82, x = 77.54, QA = 3448, zone = "Ironforge"},
{ str = "Turn in #TURNINPassing the Burden#  \nAccept #ACCEPTArcane Runes#  \nAccept #ACCEPTAn Easy Pickup#", y = 4.82, x = 30.96, QA = {3449,3450}, zone = "Ironforge", QT = 3448},
{ str = "Set your HS to Ironforge", y = 51.59, x = 18.1, zone = "Ironforge", typ = "home"},
{ str = "Accept #ACCEPTThe Hunter's Charm#", y = 83.6, x = 70.9, QA = 8151, zone = "Ironforge"},
{ str = "Turn in #TURNINAn Easy Pickup#  \nAccept #ACCEPTSignal for Pickup#  \nTurn in #TURNINSignal for Pickup#", y = 94.56, x = 70.86, QA = 3451, zone = "Ironforge", QT = {3450,3451}},
{ str = "Fly to  Loch Modan", typ = "fly"},
{ str = "Turn in #TURNINAt Last!#", y = 84.01, x = 18.18, zone = "Loch Modan", QT = 3201},
{ str = "Fly to  The Hinterlands", typ = "fly"},
{ str = "Turn in #TURNINSkulk Rock Clean-up#  \nTurn in #TURNINThe Altar of Zul#", y = 44.56, x = 14.83, zone = "The Hinterlands", QT = {2877,2989}},
{ str = "Fly to  Western Plaguelands", typ = "fly"},
{ str = "Turn in #TURNINA Call to Arms: The Plaguelands!#\n \nAccept #ACCEPTClear the Way#", y = 84.03, x = 42.7, QA = 5092, zone = "Western Plaguelands"},
{ str = "Do #DOQUESTClear the Way#", y = 77.8, x = 50.8, zone = "Western Plaguelands", QC = 5092},
{ str = "Turn in #TURNINClear the Way#  \nAccept #ACCEPTThe Scourge Cauldrons#", y = 84.03, x = 42.7, QA = 5215, zone = "Western Plaguelands", QT = 5092},
{ str = "Turn in #TURNINThe Scourge Cauldrons#  \nAccept #ACCEPTTarget: Felstone Field#", y = 84.5, x = 42.97, QA = 5216, zone = "Western Plaguelands", QT = 5215},
{ str = "#DOQUEST*#Kill the cauldron lord\n \nClick on the cauldron \nTurn in #TURNINTarget: Felstone Field#  \nAccept #ACCEPTReturn to Chillwind Camp#", y = 56.78, x = 37.24, QA = 5217, zone = "Western Plaguelands", QT = 5216},
{ str = "Talk to Janice Felstone inside the farm house \nAccept #ACCEPTBetter Late Than Never#", y = 54.05, x = 38.4, QA = 5021, zone = "Western Plaguelands"},
{ str = "Click on the parcel inside the barn \nTurn in #TURNINBetter Late Than Never#  \nAccept #ACCEPTBetter Late Than Never#", y = 55.24, x = 38.72, QA = 5022, zone = "Western Plaguelands", QT = 5021},
{ str = "Grind until you are 16950 XP away from 52  \nIf you are not yet close, do one more cauldron quest to get you where you need to be\n \nTurn in #TURNINReturn to Chillwind Camp#  \nYou can death skip to chillwind camp if you are at or close to level 52", y = 84.5, x = 42.97, zone = "Western Plaguelands", QT = 5217},
{ str = "Accept #ACCEPTTarget: Dalson's Tears#\nKill the cauldron and lord  \nTurn in #TURNINTarget: Dalson's Tears#  \nAccept #ACCEPTReturn to Chillwind Camp#\nTurn in #TURNINReturn to Chillwind Camp# \nSkip the Dalson's Tear quest line if you don't need more XP\n \nGrind until you are 14300 XP away from level 52", y = 52, x = 46.2, zone = "Western Plaguelands"},
{ str = "Hearth to Ironforge if your HS is off cooldown\n \nFly to  Wetlands", typ = "fly"},
		}
	},

-----------41-42 Desolace
	--[403] = {
	[4142] = {
		title = "52-52 Felwood",
		--n = "41-42 Desolace",
		--pID = 402, nID = 404,
		--itemCount = 16,
		items = {



{ str = "Take the boat to Darkshore \n \nSet your HS to Auberdine", typ = "home"},
{ str = "Fly to  Teldrassil", typ = "fly"},
{ str = "Turn in #TURNINFavored of Elune?#", y = 92.04, x = 55.49, zone = "Teldrassil", QT = 3661},
{ str = "Accept #ACCEPTMoontouched Wildkin#  \nIf you are not yet level 52, skip this step", y = 92.04, x = 55.49, QA = 978, zone = "Teldrassil"},
{ str = "Turn in #TURNINThe Super Snapper FX#  \nAccept #ACCEPTReturn to Troyas#", y = 92.23, x = 55.41, QA = 2943, zone = "Teldrassil", QT = 2944},
{ str = "Withdraw the following items: \nJer'kai's Signet Ring \nRaschal's Report \nInsect Analysis Report \nLinken's Training Sword \nPackage of Empty Ooze Containers \nBloodpetal \n \nDeposit the follwing items:  \nJanice's Parcel \nFlare gun \nDrawing kit "},
{ str = "Train skills \nRestock on supplies, long grinding session ahead\nAccept #ACCEPTThe Hunter's Charm#\n \nTurn in #TURNINRise of the Silithid# \nAccept #ACCEPTMarch of the Silithid#", y = 85.62, x = 41.83, QA = 4493, zone = "Darnassus", QT = 162},
{ str = "Turn in #TURNINRise of the Silithid#", y = 85.62, x = 41.83, zone = "Darnassus", QT = 4267},
{ str = "Turn in #TURNINDoling Justice#", y = 81.58, x = 39.09, zone = "Darnassus", QT = 2972},
{ str = "Fly to  Azshara", typ = "fly"},
{ str = "Accept #ACCEPTSpiritual Unrest#  \nAccept #ACCEPTA Land Filled with Hatred#", y = 78.16, x = 11.36, QA = {5535,5536}, zone = "Azshara"},
{ str = "Do #DOQUESTSpiritual Unrest#\n \nDo #DOQUESTA Land Filled with Hatred#  \nMake sure to prioritize satyrs", y = 61.79, x = 20.09, zone = "Azshara", QC = 5536},
{ str = "Turn in #TURNINSpiritual Unrest#  \nTurn in #TURNINA Land Filled with Hatred#", y = 78.16, x = 11.36, zone = "Azshara", QT = {5535,5536}},
{ str = "Head to Felwood \n \nAccept #ACCEPTCleansing Felwood#", y = 86.83, x = 54.14, QA = 4101, zone = "Felwood"},
{ str = "Accept #ACCEPTTimbermaw Ally#", y = 85, x = 50.92, QA = 8460, zone = "Felwood"},
{ str = "Run to the Emerald Sanctuary \nAccept #ACCEPTForces of Jaedenar#  \nAccept #ACCEPTVerifying the Corruption#  \nAccept #ACCEPTThe Corruption of the Jadefire#", y = 82.1, x = 51.21, QA = {5155,5156,4421}, zone = "Felwood"},
{ str = "#DOQUEST*#Kill slimes, use the Ooze jar on their corpses", y = 66.86, x = 40.77, zone = "Felwood", QC = { [4512] = 1}},
{ str = "Do #DOQUESTThe Corruption of the Jadefire#", y = 67.04, x = 32.27, zone = "Felwood", QC = 4421},
{ str = "#DOQUEST*#Kill slimes, use the Ooze jar on their corpses\n \nDo #DOQUESTForces of Jaedenar#", y = 60.72, x = 38.45, zone = "Felwood", QC = 5155},
{ str = "Finish off #DOQUESTA Little Slime Goes a Long Way#", y = 59.06, x = 40.48, zone = "Felwood", QC = { [4512] = 2}},
{ str = "Turn in #TURNINForces of Jaedenar#  \nAccept #ACCEPTCollection of the Corrupt Water#", y = 82.1, x = 51.21, QA = 5157, zone = "Felwood", QT = 5155},
{ str = "Turn in #TURNINThe Corruption of the Jadefire#", y = 81.5, x = 51.34, zone = "Felwood", QT = 4421},
{ str = "Accept #ACCEPTFurther Corruption#", y = 81.5, x = 51.34, QA = 4906, zone = "Felwood"},
{ str = "Accept #ACCEPTVerifying the Corruption#", y = 81.61, x = 50.88, QA = 5156, zone = "Felwood"},
{ str = "Accept #ACCEPTTimbermaw Ally#", y = 85, x = 50.92, QA = 8460, zone = "Felwood"},
{ str = "Do #DOQUESTTimbermaw Ally#", y = 90.22, x = 48.93, zone = "Felwood", QC = 8460},
{ str = "Turn in #TURNINTimbermaw Ally#  \nAccept #ACCEPTSpeak to Nafien#", y = 85, x = 50.92, QA = 8462, zone = "Felwood", QT = 8460},
{ str = "Grind fulborgs until you get unfriendly with Timbermaw Hold \n  \nKeep grinding fulborgs until you have enough Mageweave for alliance cloth turn ins (12 stacks) \nYou can skip the mageweave farm if you can afford to buy it from the AH"},
{ str = "#DOQUEST*#Fill the empty canteen at the Jaedenar moonwell", y = 59.76, x = 35.15, zone = "Felwood", QC = 5157},
{ str = "Do #DOQUESTVerifying the Corruption#", y = 40.2, x = 44.03, zone = "Felwood", QC = 5156},
{ str = "Kill Xavaric \nAccept #ACCEPTFlute of Xavaric#", y = 22.3, x = 39.06, QA = 939, zone = "Felwood"},
{ str = "Do #DOQUESTFurther Corruption#  \nDo #DOQUESTFlute of Xavaric#", y = 19.36, x = 41.81, zone = "Felwood", QC = { [4906] = 0, [939] = 0}},
{ str = "Do #DOQUESTCleansing Felwood#", y = 17, x = 56.1, zone = "Felwood", QC = 4101},
{ str = "Vendor stuff, you gonna spirit rez 3 times on the next segment\n \nGet the  Felwood FP", y = 24.24, x = 62.5, zone = "Felwood", typ = "fp"},
{ str = "Turn in #TURNINSpeak to Nafien#", y = 8.12, x = 64.76, zone = "Felwood", QT = 8462},
{ str = "Run to Winterspring \nTurn in #TURNINIt's a Secret to Everybody#  \nAccept #ACCEPTThe Videre Elixir#", y = 45.16, x = 31.26, QA = 3909, zone = "Winterspring", QT = 3908},
{ str = "Look for Moontouched feathers on the ground \nSkip this step if you don't have this quest \n(#DOQUESTMoontouched Wildkin#)", y = 43.39, x = 43.78, zone = "Winterspring", QC = 978},
{ str = "Die and spirit rez at Everlook\nStable your pet \n \nFly to  Felwood", typ = "fly"},
{ str = "Tame a Felpaw Ravager, learn bite 7 "},
{ str = "Death warp to the graveyard\nTame an Ironbeak Hunter or Angerclaw Mauler and learn claw 7 \n \n Run south to the slime pond \nDeath warp to southern felwood", y = 66.77, x = 40.84, zone = "Felwood"},
{ str = "Turn in #TURNINCleansing Felwood#", y = 86.83, x = 54.14, zone = "Felwood", QT = 4101},
{ str = "Make sure you have a Cenarion Beacon", y = 86.82, x = 54.14, zone = "Felwood"},
{ str = "Turn in #TURNINCollection of the Corrupt Water#  \nAccept #ACCEPTSeeking Spiritual Aid#", y = 82.1, x = 51.21, QA = 5158, zone = "Felwood", QT = 5157},
{ str = "Turn in #TURNINFlute of Xavaric#  \nAccept #ACCEPTFelbound Ancients#  \nTurn in #TURNINFurther Corruption#", y = 81.5, x = 51.34, QA = 4441, zone = "Felwood", QT = {939,4906}},
{ str = "Turn in #TURNINVerifying the Corruption#", y = 81.61, x = 50.88, zone = "Felwood", QT = 5156},
{ str = "Hearth to Darkshore\nWithdraw your pet from the stables \n \nFly to  Feathermoon", typ = "fly"},
		}
	},
-----------42-43 Stranglethron Vale
	--[404] = {
	[4243] = {
		title = "52-53 Feralas",
		--n = "42-43 Stranglethron Vale",
		--pID = 403, nID = 405,
		--itemCount = 29,
		items = {

{ str = "Withdraw your pet from the stables \n \nAccept #ACCEPTImproved Quality#", y = 42.7, x = 30.63, QA = 7733, zone = "Feralas"},
{ str = "Set your HS to Feathermoon", typ = "home"},
{ str = "Turn in #TURNINReturn to Troyas#  \nAccept #ACCEPTThe Stave of Equinex#", y = 45.5, x = 31.78, QA = 2879, zone = "Feralas", QT = 2943},
{ str = "Swim to the mainland\n \nAccept #ACCEPTZapped Giants#  \nAccept #ACCEPTFuel for the Zapping#", y = 43.42, x = 44.81, QA = {7003,7721}, zone = "Feralas"},
{ str = "Do #DOQUESTZapped Giants#  \nDo #DOQUESTFuel for the Zapping#", y = 62.73, x = 46.12, zone = "Feralas", QC = { [7003] = 0, [7721] = 0}},
{ str = "Turn in #TURNINZapped Giants#  \nTurn in #TURNINFuel for the Zapping#", y = 43.42, x = 44.81, zone = "Feralas", QT = {7003,7721}},
{ str = "Grind Yetis until you get a pristine hide \nAccept #ACCEPTPristine Yeti Hide#\n \nDo #DOQUESTImproved Quality#", y = 32.84, x = 54.84, zone = "Feralas", QC = 7733},
{ str = "Turn in #TURNINA Visit to Gregan#", y = 25.56, x = 45.12, zone = "Feralas", QT = 4142},
{ str = "Buy some bait from Gregan", y = 25.56, x = 45.12, zone = "Feralas"},
{ str = "Accept #ACCEPTThe Giant Guardian#", y = 21.99, x = 42.38, QA = 2844, zone = "Feralas"},
{ str = "Give some bait to the gnoll guarding the Evoroot", y = 10.59, x = 44.64, zone = "Feralas"},
{ str = "#DOQUEST*#Loot all 4 flames  \nRight click on Troyas' Staff at the monolith", y = 13.12, x = 38.88, zone = "Feralas", QC = 2879},
{ str = "Click on the monolith \nTurn in #TURNINThe Stave of Equinex#  \nAccept #ACCEPTThe Morrow Stone#", y = 13.17, x = 38.82, QA = 2942, zone = "Feralas", QT = 2879},
{ str = "Grind harpies until your HS cooldown is <8 minutes"},
{ str = "Turn in #TURNINThe Giant Guardian#  \nAccept #ACCEPTWandering Shay#", y = 10.29, x = 38.22, QA = 2845, zone = "Feralas", QT = 2844},
{ str = "#DOQUEST*#Loot the chest next to the quest giver", y = 10.29, x = 38.25, zone = "Feralas", QC = { [2845] = 1}},
{ str = "#DOQUEST*#Escort Shay", y = 21.99, x = 42.38, zone = "Feralas", QC = 2845},
{ str = "Turn in #TURNINWandering Shay#", y = 21.99, x = 42.38, zone = "Feralas", QT = 2845},
{ str = "#DOQUEST*#Talk to Gregan and trade in the Evoroot", y = 25.56, x = 45.12, zone = "Feralas", QC = 3909},
{ str = "Die and spirit rez, head towards Dire Maul and skip this step once the General Chat changes to Dire Maul (this is a pre requisite for a Moonglade quest later) \nHearth back to Feathermoon\n \nTurn in #TURNINThe Morrow Stone#", y = 45.5, x = 31.78, zone = "Feralas", QT = 2942},
{ str = "Turn in #TURNINPristine Yeti Hide#\n \nTurn in #TURNINImproved Quality#", y = 42.7, x = 30.63, zone = "Feralas", QT = 7733},
{ str = "Fly to  Ratchet", typ = "fly"},
		}
	},

-----------43-43 Tanaris
	--[405] = {
	[4343] = {
		title = "53-53 Azshara",
		--n = "43-43 Tanaris",
		--pID = 404, nID = 406,
		--itemCount = 34,
		items = {

{ str = "Make sure you have at least 1 stack of noggenfogger for this next segment\nWithdraw the following: \nDrawing Kit \nFlare Gun \n \nDeposit the follwing items: \nEridan's Vial \nCenarion Beacon \nFilled Cursed Ooze Jar \nFilled Tainted Ooze Jar "},
{ str = "Set your HS to Ratchet", typ = "home"},
{ str = "Buy extra supplies, long grinding session ahead\n \nFly to  Azshara", typ = "fly"},
{ str = "Turn in #TURNINThe Hunter's Charm#  \nAccept #ACCEPTCourser Antlers# ", y = 42.6, x = 42.37, QA = 8153, zone = "Azshara", QT = 8151},
{ str = "#DOQUEST*#Kill mosshoof coursers as you quest \n \nAccept #ACCEPTKim'jael Indeed!#", y = 21.82, x = 53.45, QA = 3601, zone = "Azshara"},
{ str = "#DOQUEST*#Loot the boxes scattered around the camp", y = 29.44, x = 57.02, zone = "Azshara", QC = 3601},
{ str = "Turn in #TURNINKim'jael Indeed!#  \nAccept #ACCEPTKim'jael's \"Missing\" Equipment#", y = 21.82, x = 53.45, QA = 5534, zone = "Azshara", QT = 3601},
{ str = "Kill nagas for #DOQUESTKim'jael's \"Missing\" Equipment#\n \n#DOQUEST*#Click on the first monolith", y = 50.31, x = 39.57, zone = "Azshara", QC = { [3449] = 2}},
{ str = "#DOQUEST*#Click on the second monolith", y = 53.18, x = 36.95, zone = "Azshara", QC = { [3449] = 1}},
{ str = "#DOQUEST*#Click on the third monolith", y = 55.42, x = 39.33, zone = "Azshara", QC = { [3449] = 4}},
{ str = "#DOQUEST*#Click on the fourth monolith", y = 64.14, x = 42.34, zone = "Azshara", QC = { [3449] = 8}},
{ str = "Turn in #TURNINKim'jael's \"Missing\" Equipment#", y = 21.82, x = 53.45, zone = "Azshara", QT = 5534},
{ str = "Grind elves until you are 40% into level 53 "},
{ str = "Grind until your HS cooldown is <5 minutes\n \nTurn in #TURNINCourser Antlers# ", y = 42.61, x = 42.39, zone = "Azshara", QT = 8153},
{ str = "Go behind the giant statue \nUse noggenfoger to jump down to the small island east \nUse the flare gun at the landing pad \nTurn in #TURNINArcane Runes#  \nAccept #ACCEPTReturn to Tymor#", y = 87.87, x = 73.21, QA = 3461, zone = "Azshara", QT = 3449},
{ str = "Destroy the flare gun\nHearth to Ratchet\n \nTurn in #TURNINSeeking Spiritual Aid#  \nAccept #ACCEPTCleansed Water Returns to Felwood#", y = 43.77, x = 65.82, QA = 5159, zone = "The Barrens", QT = 5158},
{ str = "Accept #ACCEPTVolcanic Activity#", y = 38.73, x = 62.44, QA = 4502, zone = "The Barrens"},
{ str = "#DOQUEST*#Loot the small chest outside the metal hut", y = 38.54, x = 62.5, zone = "The Barrens", QC = 3444},
{ str = "Deposit the following items: \nDrawing kit \nPurified Moonwell Water \n \nFly to  Tanaris", typ = "fly"},
		}
	},

-----------43-45 Feralas
	--[406] = {
	[4345] = {
		title = "53-54 Un'Goro Crater",
		--n = "43-45 Feralas",
		--pID = 405, nID = 407,
		--itemCount = 43,
		items = {


{ str = "Withdraw the follwing items: \nTorwa's Pouch \nWebbed Diemetradon Scale \nWebbed Pterrordax Scale \nDinosaur Bone "},
{ str = "Turn in #TURNINMarch of the Silithid#  \nAccept #ACCEPTBungle in the Jungle#", y = 26.96, x = 50.88, QA = 4496, zone = "Tanaris", QT = 4493},
{ str = "Turn in #TURNINThe Stone Circle# ", y = 45.92, x = 52.7, zone = "Tanaris", QT = 3444},
{ str = "Fly to  Un'Goro", typ = "fly"},
{ str = "Accept #ACCEPTExpedition Salvation#  \nAccept #ACCEPTAlien Ecology#", y = 7.13, x = 43.94, QA = {3881,3883}, zone = "Un'Goro Crater"},
{ str = "Accept #ACCEPTRoll the Bones#", y = 7.42, x = 43.49, QA = 3882, zone = "Un'Goro Crater"},
{ str = "Turn in #ACCEPT*##TURNINCrystals of Power#\n \nAccept #ACCEPTThe Northern Pylon#  \nAccept #ACCEPTThe Western Pylon#  \nAccept #ACCEPTThe Eastern Pylon#", y = 2.69, x = 41.91, QA = {4288,4287,4285}, zone = "Un'Goro Crater"},
{ str = "Click on the Wanted Poster \nAccept #ACCEPTBeware of Pterrordax#", y = 8.43, x = 43.52, QA = 4501, zone = "Un'Goro Crater"},
{ str = "Accept #ACCEPTLost!#", y = 8.49, x = 43.61, QA = 4492, zone = "Un'Goro Crater"},
{ str = "Accept #ACCEPTShizzle's Flyer#", y = 11.58, x = 44.23, QA = 4503, zone = "Un'Goro Crater"},
{ str = "#DOQUEST*##DOQUEST*#Kill diametradons as you quest through Un'Goro\nStart working on #DOQUESTBeware of Pterrordax#\n \n#DOQUEST*#Click on the Northern Pylon", y = 12.5, x = 56.49, zone = "Un'Goro Crater", QC = 4285},
{ str = "Do #DOQUESTThe Apes of Un'Goro#", y = 15.47, x = 67.67, zone = "Un'Goro Crater", QC = 4289},
{ str = "#DOQUEST*#Loot the Crate of Foodstuffs", y = 36.52, x = 68.47, zone = "Un'Goro Crater", QC = { [3881] = 1}},
{ str = "#DOQUEST*#Right click on the eastern pylon", y = 49.85, x = 77.2, zone = "Un'Goro Crater", QC = 4287},
{ str = "#DOQUEST*#Open Torwa's Pouch, set up the threshadon meat and the pheromone mixture and kill Lar'kowi", y = 49.86, x = 79.95, zone = "Un'Goro Crater", QC = 4292},
{ str = "Turn in #TURNINThe Bait for Lar'korwi#  \nTurn in #TURNINThe Apes of Un'Goro#  \nAccept #ACCEPTThe Mighty U'cha#", y = 75.95, x = 71.63, QA = 4301, zone = "Un'Goro Crater", QT = {4292,4289}},
{ str = "#DOQUEST*#Kill Pterrodaxes", y = 90.37, x = 56.46, zone = "Un'Goro Crater", QC = { [4501] = 1}},
{ str = "#DOQUEST*#Enter the silithid hive \nUse the scraping vial on the middle of the room", y = 85.37, x = 48.67, zone = "Un'Goro Crater", QC = 3883},
{ str = "Keep killing bugs until you get a #DOQUESTGorishi Scent Gland#", y = 81.58, x = 44.65, zone = "Un'Goro Crater", QC = { [4496] = 1}},
{ str = "#DOQUEST*#Kill any Frenzied Pterrodax you see\n \n#DOQUEST*#Loot the Research Equipment", y = 66.01, x = 38.43, zone = "Un'Goro Crater", QC = { [3881] = 2}},
{ str = "#DOQUEST*#Click on the Western Pylon", y = 59.08, x = 23.84, zone = "Un'Goro Crater", QC = 4288},
{ str = "Accept #ACCEPTFinding the Source#", y = 50.43, x = 30.92, QA = 974, zone = "Un'Goro Crater"},
{ str = "#DOQUEST*#Kill fire elementals\n \n#DOQUEST*#Climb to the top of the volcano and use the quest item on the flaming protuberance", y = 45.72, x = 49.75, zone = "Un'Goro Crater", QC = 974},
{ str = "Finish off #DOQUESTVolcanic Activity#", y = 53.88, x = 47.05, zone = "Un'Goro Crater", QC = 4502},
{ str = "Turn in #TURNINFinding the Source#  \nAccept #ACCEPTThe New Springs#", y = 50.43, x = 30.92, QA = 980, zone = "Un'Goro Crater", QT = 974},
{ str = "Finish off the following: \n#DOQUESTBeware of Pterrordax#  \n#DOQUESTShizzle's Flyer# \n#DOQUESTRoll the Bones#", y = 33.16, x = 36.75, zone = "Un'Goro Crater", QC = { [4501] = 0, [3882] = 0, [4503] = 0}},
{ str = "Start the Ringo escort quest \nTurn in #TURNINLost!#  \nAccept #ACCEPTA Little Help From My Friends#", y = 49.84, x = 51.9, QA = 4491, zone = "Un'Goro Crater", QT = 4492},
{ str = "#DOQUEST*#Escort Ringo to Marshal's Refuge \nTurn in #TURNINA Little Help From My Friends#", y = 8.49, x = 43.61, zone = "Un'Goro Crater", QC = 4491, QT = 4491},
{ str = "Turn in #TURNINBeware of Pterrordax#", y = 8.49, x = 43.61, zone = "Un'Goro Crater", QT = 4501},
{ str = "Turn in #TURNINRoll the Bones#", y = 7.42, x = 43.49, zone = "Un'Goro Crater", QT = 3882},
{ str = "Turn in #TURNINAlien Ecology#  \nTurn in #TURNINExpedition Salvation#", y = 7.23, x = 43.88, zone = "Un'Goro Crater", QT = {3883,3881}},
{ str = "Turn in #TURNINThe Northern Pylon#  \nTurn in #TURNINThe Eastern Pylon#  \nTurn in #TURNINThe Western Pylon#  \nTurn in #ACCEPT*##TURNINMaking Sense of It#", y = 2.69, x = 41.91, QA = 4321, zone = "Un'Goro Crater", QT = {4285,4321,4287,4288}},
{ str = "Turn in #TURNINShizzle's Flyer#", y = 11.58, x = 44.23, zone = "Un'Goro Crater", QT = 4503},
{ str = "Accept #ACCEPTChasing A-Me 01#", y = 13.44, x = 46.37, QA = 4243, zone = "Un'Goro Crater"},
{ str = "Turn in #TURNINChasing A-Me 01#", y = 16.76, x = 67.65, zone = "Un'Goro Crater", QT = 4243},
{ str = "Do #DOQUESTThe Mighty U'cha#", y = 12.47, x = 68.4, zone = "Un'Goro Crater", QC = 4301},
{ str = "Turn in #TURNINThe Mighty U'cha#", y = 75.95, x = 71.63, zone = "Un'Goro Crater", QT = 4301},
{ str = "Make sure you have 20 Un'Goro soil before leaving Un'Goro\nHearth to Ratchet \nYou can also pull a mob, death skip at the Tanaris border and use HS batching in Gadgetzan to save you 5 minutes later on\n \nTurn in #TURNINVolcanic Activity# ", y = 38.73, x = 62.44, zone = "The Barrens", QT = 4502},
{ str = "Withdraw the following:  \nEridan's vial \nPurified Moonwell Water \nCenarion beacon \nMoontouched Feathers \n \nFly to  Teldrassil", typ = "fly"},
{ str = "Accept #ACCEPTMoontouched Wildkin#", y = 92.04, x = 55.49, QA = 978, zone = "Teldrassil"},
{ str = "Turn in #TURNINMoontouched Wildkin#  \nAccept #ACCEPTFind Ranshalla#  \nSkip this step if you just got this quest (Moontouched Wildkin)", y = 92.04, x = 55.49, QA = 979, zone = "Teldrassil", QT = 978},
{ str = "Run upstairs \nAccept #ACCEPTStarfall#", y = 92.23, x = 55.41, QA = 5250, zone = "Teldrassil"},
{ str = "Do the Darnassus cloth turn ins: \n#ACCEPT*##TURNIN*#Wool  \n#ACCEPT*##TURNIN*#Silk  \n#ACCEPT*##TURNIN*#Mageweave  \n#ACCEPT*##TURNIN*#Runecloth", y = 22.79, x = 63.8, QA = {7798,7799,7800,7792}, zone = "Darnassus", QT = {7798,7799,7800,7792}},
{ str = "Accept #ACCEPTThe New Frontier# from the courier that roams Darnassus\n \n#DOQUEST*#Use Eridan's Vial at the fountain inside the temple", y = 85.12, x = 39.19, zone = "Darnassus", QC = 4441},
{ str = "Buy food/water\n \nAccept #ACCEPTAssisting Arch Druid Staghelm#", y = 15.67, x = 67.38, QA = 3763, zone = "Darnassus"},
{ str = "Accept #ACCEPTThe New Frontier# from the courier that roams Darnassus", y = 81.96, x = 47.8, QA = 1047, zone = "Darnassus"},
{ str = "Turn in #TURNINThe New Frontier#\n \nAccept #ACCEPTThe New Frontier# \nTurn in #TURNINAssisting Arch Druid Staghelm#  \nAccept #ACCEPTUn'Goro Soil# ", y = 9.25, x = 34.81, QA = {6761,3764}, zone = "Darnassus", QT = 3763},
{ str = "Jump down and turn in #TURNINUn'Goro Soil#", y = 8.23, x = 31.48, zone = "Darnassus", QT = 3764},
{ str = "Run upstairs and speak with the Arch Druid \nAccept #ACCEPTMorrowgrain Research#", y = 9.25, x = 34.81, QA = 3781, zone = "Darnassus"},
{ str = "Run down to the middle floor, speak with Mathrengyl Bearwalker\nTurn in #TURNINThe New Frontier#\n \nAccept #ACCEPTRabine Saturna#  ", y = 8.4, x = 35.37, QA = 6762, zone = "Darnassus"},
{ str = "Turn in #TURNINMorrowgrain Research# at the middle floor", y = 8.4, x = 35.37, zone = "Darnassus", QT = 3781},
{ str = "Fly to  Felwood", typ = "fly"},
		}
	},

-----------45-46 Uldaman
	--[407] = {
	[4546] = {
		title = "54-55 Felwood/Winterspring",
		--n = "45-46 Uldaman",
		--pID = 406, nID = 408,
		--itemCount = 7,
		items = {


{ str = "Collect 6 Corrupted Soul Shards\n \nGo inside the small hut and turn in #TURNINFelbound Ancients# first", y = 81.5, x = 51.34, zone = "Felwood", QT = 4441},
{ str = "Turn in #TURNINCleansed Water Returns to Felwood#  \nAccept #ACCEPTDousing the Flames of Protection#", y = 82.1, x = 51.21, QA = 5165, zone = "Felwood", QT = 5159},
{ str = "Accept #ACCEPTPurified!#  \nTurn in #TURNINPurified!#", y = 81.5, x = 51.34, QA = 4442, zone = "Felwood", QT = 4442},
{ str = "Turn in #ACCEPT*##TURNINSalve via Hunting#", y = 86.8, x = 54.2, QA = 5882, zone = "Felwood", QT = 5882},
{ str = "Run to Jaedenar \n#DOQUEST*#Douse the first flame", y = 56.3, x = 36.26, zone = "Felwood", QC = { [5165] = 1}},
{ str = "Keep grinding mobs until you get the Blood Red Key \nAccept #ACCEPTA Strange Red Key#\n \n#DOQUEST*#Douse the second flame", y = 55.18, x = 36.48, zone = "Felwood", QC = { [5165] = 8}},
{ str = "#DOQUEST*#Douse the third flame", y = 53.26, x = 36.73, zone = "Felwood", QC = { [5165] = 4}},
{ str = "#DOQUEST*#Douse the fourth flame", y = 52.68, x = 37.67, zone = "Felwood", QC = { [5165] = 2}},
{ str = "Start the escort quest \nTurn in #TURNINA Strange Red Key#\n \nAccept #ACCEPTRescue From Jaedenar#", y = 55.46, x = 36.2, QA = 5203, zone = "Felwood"},
{ str = "#DOQUEST*#Escort Arko'narin", QC = 5203},
{ str = "Stop by the northern GY, right click on the flute of the ancients and start the escort quest \n(#ACCEPTAncient Spirit#)", y = 29.7, x = 49.55, QA = 4261, zone = "Felwood"},
{ str = "#DOQUEST*#Escort Arei", QC = 4261},
{ str = "Accept #ACCEPTDeadwood of the North#", y = 8.12, x = 64.76, QA = 8461, zone = "Felwood"},
{ str = "Do #DOQUESTDeadwood of the North#", y = 11.16, x = 62.59, zone = "Felwood", QC = 8461},
{ str = "Turn in #TURNINDeadwood of the North#  \nAccept #ACCEPTSpeak to Salfa#", y = 8.12, x = 64.76, QA = 8465, zone = "Felwood", QT = 8461},
{ str = "Run to Winterspring \nTurn in #TURNINSpeak to Salfa#  \nAccept #ACCEPTWinterfall Activity#", y = 34.49, x = 27.73, QA = 8464, zone = "Winterspring", QT = 8465},
{ str = "Turn in #TURNINThe Videre Elixir#  \nAccept #ACCEPTMeet at the Grave# ", y = 45.16, x = 31.26, QA = 3912, zone = "Winterspring", QT = 3909},
{ str = "Turn in #TURNINThe New Springs#  \nAccept #ACCEPTStrange Sources#  \nAccept #ACCEPTThreat of the Winterfall#", y = 45.16, x = 31.26, QA = {4842,5082}, zone = "Winterspring", QT = 980},
{ str = "Do #DOQUESTThreat of the Winterfall#", y = 36.04, x = 30.59, zone = "Winterspring", QC = 5082},
{ str = "Keep grinding fulborgs until you get an Empty Firewater Flask \nAccept #ACCEPTWinterfall Firewater#", y = 35.52, x = 67.17, QA = 5083, zone = "Winterspring"},
{ str = "Turn in #TURNINThreat of the Winterfall#  \nTurn in #TURNINWinterfall Firewater#  \nAccept #ACCEPTFalling to Corruption#", y = 45.16, x = 31.26, QA = 5084, zone = "Winterspring", QT = {5082,5083}},
{ str = "Run back to Felwood \nTurn in #TURNINFalling to Corruption#  \nAccept #ACCEPTMystery Goo#", y = 5.84, x = 60.2, QA = 5085, zone = "Felwood", QT = 5084},
{ str = "Run back to Winterspring \nTurn in #TURNINMystery Goo#  \nAccept #ACCEPTToxic Horrors#", y = 19.24, x = 72.66, QA = 5086, zone = "Felwood", QT = 5085},
{ str = "#DOQUEST*#Look for blue feathers on the ground \nSkip this step if you did this quest earlier", y = 17.06, x = 88.12, zone = "Felwood", QC = 978},
{ str = "Fly to Teldrassil\nTurn in #TURNINMoontouched Wildkin#\n \nAccept #ACCEPTFind Ranshalla# \nSkip this step if you have this quest already", y = 92.04, x = 55.49, QA = 979, zone = "Teldrassil"},
{ str = "Hearth to Ratchet or Tanaris\n \nFly to  Tanaris", typ = "fly"},
{ str = "Accept #ACCEPTSuper Sticky#", y = 26.75, x = 51.56, QA = 4504, zone = "Tanaris"},
{ str = "Turn in #TURNINBungle in the Jungle#", y = 26.96, x = 50.88, zone = "Tanaris", QT = 4496},
{ str = "Use the Videre Elixir at the Tanaris graveyard\n \nSpeak to the ghost just north of the graveyard, you can only see him while dead \nTurn in #TURNINMeet at the Grave#  \nAccept #ACCEPTA Grave Situation#", y = 23.33, x = 53.93, QA = 3913, zone = "Tanaris", QT = 3912},
{ str = "Click on the Conspicuous Gravestone \nTurn in #TURNINA Grave Situation#  \nAccept #ACCEPTLinken's Sword#", y = 29.06, x = 53.81, QA = 3914, zone = "Tanaris", QT = 3913},
{ str = "Fly to  Un'Goro", typ = "fly"},
{ str = "Turn in #TURNINLinken's Sword#  \nAccept #ACCEPTA Gnome's Assistance#", y = 8.09, x = 44.65, QA = 3941, zone = "Un'Goro Crater", QT = 3914},
{ str = "Turn in #TURNINA Gnome's Assistance#  \nAccept #ACCEPTLinken's Memory#", y = 2.69, x = 41.91, QA = 3942, zone = "Un'Goro Crater", QT = 3941},
{ str = "Do #DOQUESTSuper Sticky#", y = 26.37, x = 51.5, zone = "Un'Goro Crater", QC = 4504},
{ str = "Fly to  Tanaris", typ = "fly"},
{ str = "Turn in #TURNINSuper Sticky#", y = 26.75, x = 51.56, zone = "Tanaris", QT = 4504},
{ str = "Fly to  Azshara", typ = "fly"},
{ str = "Run to Ashenvale \nTurn in #TURNINAncient Spirit#", y = 44.71, x = 85.23, zone = "Ashenvale", QT = 4261},
{ str = "Throw away the Flute of the Ancients\n \nRun to Felwood \nTurn in #ACCEPT*##TURNINSalve via Hunting#", y = 86.84, x = 54.15, QA = 5882, zone = "Felwood", QT = 5882},
{ str = "Turn in #TURNINDousing the Flames of Protection#  \nAccept #ACCEPTA Final Blow#", y = 82.1, x = 51.21, QA = 5242, zone = "Felwood", QT = 5165},
{ str = "Turn in #TURNINRescue From Jaedenar#  \nAccept #ACCEPTRetribution of the Light#", y = 82.01, x = 51.34, QA = 5204, zone = "Felwood", QT = 5203},
{ str = "Turn in #TURNINLinken's Memory#  \nAccept #ACCEPTSilver Heart#", y = 81.5, x = 51.34, QA = 4084, zone = "Felwood", QT = 3942},
{ str = "Run to Jaedenar, enter the Shadow Hold \n#DOQUEST*#Kill Rakaiah\n \nTurn in #TURNINRetribution of the Light#  \nAccept #ACCEPTThe Remains of Trey Lightforge#", y = 50.4, x = 38.49, QA = 5385, zone = "Felwood", QT = 5204},
{ str = "Go deeper into the Shadow Hold \nDo #DOQUESTA Final Blow#", y = 46.79, x = 38.86, zone = "Felwood", QC = 5242},
{ str = "#DOQUEST*#Kill Bears/Wolves as you go through Felwood\n \nDo #DOQUESTToxic Horrors#", y = 25.09, x = 49.52, zone = "Felwood", QC = 5086},
{ str = "#DOQUEST*#Kill Irontree Stompers", y = 19.86, x = 49.67, zone = "Felwood", QC = { [4084] = 2}},
{ str = "Finish off #DOQUESTSilver Heart# \nGo to Winterspring through the fulborg tunnel", y = 7.1, x = 65.4, zone = "Felwood", QC = 4084},
		}
	},

-----------46-47 The Hinterlands
	--[408] = {
	[4647] = {
		title = "55-56 Winterspring",
		--n = "46-47 The Hinterlands",
		--pID = 407, nID = 409,
		--itemCount = 29,
		items = {


{ str = "Run to Winterspring \nTurn in #TURNINToxic Horrors#  \nAccept #ACCEPTWinterfall Runners#", y = 45.16, x = 31.26, QA = 5087, zone = "Winterspring", QT = 5086},
{ str = "#DOQUEST*#Look for winterfall runners as you quest\n \nTurn in #TURNINStarfall#  \nAccept #ACCEPTThe Ruins of Kel'Theril#", y = 30.38, x = 51.97, QA = 5244, zone = "Winterspring", QT = 5250},
{ str = "Accept #ACCEPTEnraged Wildkin#  \nTurn in #TURNINThe Ruins of Kel'Theril#  \nAccept #ACCEPTTroubled Spirits of Kel'Theril#", y = 30.42, x = 52.13, QA = {4861,5245}, zone = "Winterspring", QT = 5244},
{ str = "#DOQUEST*#Loot the first relic", y = 41.71, x = 50.88, zone = "Winterspring", QC = { [5245] = 2}},
{ str = "#DOQUEST*#Loot the second relic", y = 41.5, x = 52.42, zone = "Winterspring", QC = { [5245] = 8}},
{ str = "#DOQUEST*#Loot the third relic", y = 43.43, x = 53.3, zone = "Winterspring", QC = { [5245] = 4}},
{ str = "#DOQUEST*#Loot the fourth relic", y = 42.98, x = 55.13, zone = "Winterspring", QC = { [5245] = 1}},
{ str = "Set your Hearthstone to Everlook", y = 38.89, x = 61.3, zone = "Winterspring", typ = "home"},
{ str = "Accept #ACCEPTDuke Nicholas Zverenhoff#  \nAccept #ACCEPTThe Everlook Report#  \nAccept #ACCEPTSister Pamela#", y = 38.97, x = 61.34, QA = {6028,6030,5601}, zone = "Winterspring"},
{ str = "Deposit the following items: \nEverlook report \nStudies in spirit speaking \nRabine's Letter \nCenarion Beacon \nSilvery Claws \nIrontree Heart \nRemains of Trey Lightforge \nShadow Lord Fel'dan's Head \nJaron's Pick \nAll 4 Relics "},
{ str = "Accept #ACCEPTLuck Be With You#", y = 38.29, x = 61.91, QA = 969, zone = "Winterspring"},
{ str = "Finish off #DOQUESTWinterfall Activity#  \nAbandon this quest if the village is too crowded", y = 35.48, x = 67.07, zone = "Winterspring", QC = 8464},
{ str = "Click on the damaged crate \nTurn in #TURNINEnraged Wildkin#  \nAccept #ACCEPTEnraged Wildkin#", y = 59.78, x = 58.99, QA = 4863, zone = "Winterspring", QT = 4861},
{ str = "Turn in #TURNINEnraged Wildkin#  \nAccept #ACCEPTEnraged Wildkin#", y = 60.67, x = 61.44, QA = 4864, zone = "Winterspring", QT = 4863},
{ str = "#DOQUEST*#Click on the small crate next to Jaron's Wagon", y = 60.72, x = 61.4, zone = "Winterspring", QC = { [4864] = 1}},
{ str = "#DOQUEST*#Kill Owlbeasts \nClear the thicket before starting the escort quest\n \nStart the escort quest \nTurn in #TURNINFind Ranshalla#  \nAccept #ACCEPTGuardians of the Altar#", y = 59.47, x = 63.07, QA = 4901, zone = "Winterspring", QT = 979},
{ str = "#DOQUEST*#Escort Ranshalla \nClick on the torches once she gets inside one of the caves \nRight click the stone altar at the end", QC = 4901},
{ str = "Finish off #DOQUESTEnraged Wildkin#", y = 19.96, x = 65.6, zone = "Winterspring", QC = 4864},
{ str = "#DOQUEST*#Loot the blue crystals around the outer perimeter of the canyon \nUse your pet to bait the giants away from the crystals\n \n#DOQUEST*#Run south to Darkwhisper Gorge", y = 75.23, x = 59.52, zone = "Winterspring", QC = 4842},
{ str = "Hearth to Everlook \n \nTurn in #TURNINLuck Be With You#", y = 38.29, x = 61.91, zone = "Winterspring", QT = 969},
{ str = "Turn in #TURNINEnraged Wildkin#", y = 30.42, x = 52.13, zone = "Winterspring", QT = 4864},
{ str = "Use eagle eye to find the Winterfall Runners\n \nFinish off #DOQUESTWinterfall Runners#", y = 34.68, x = 53.14, zone = "Winterspring", QC = 5087},
{ str = "Turn in #TURNINStrange Sources#  \nTurn in #TURNINWinterfall Runners#  \nAccept #ACCEPTHigh Chief Winterfall#", y = 45.16, x = 31.26, QA = 5121, zone = "Winterspring", QT = {4842,5087}},
{ str = "Turn in #TURNINWinterfall Activity#", y = 34.49, x = 27.73, zone = "Winterspring", QT = 8464},
{ str = "Unstuck back to the graveyard\n \nFly to  Teldrassil", typ = "fly"},
{ str = "Turn in #TURNINGuardians of the Altar#  \nAccept #ACCEPTWildkin of Elune#", y = 92.04, x = 55.49, QA = 4902, zone = "Teldrassil", QT = 4901},
{ str = "Withdraw the following: Drawing Kit \nFilled Cursed Ooze Jar \nFilled Tainted Ooze Jar \nJanice's Parcel \nBlack Dragonflight Molt"},
{ str = "Train skills\n \nTurn in #TURNINWildkin of Elune#", y = 9.25, x = 34.81, zone = "Darnassus", QT = 4902},
{ str = "Fly to  Darkshore", typ = "fly"},

		}
	},

-----------47-47 Feralas
	--[409] = {
	[4747] = {
		title = "56-57 Burning Steppes",
		--n = "47-47 Feralas",
		--pID = 408, nID = 410,
		--itemCount = 22,
		items = {


{ str = "Take the boat to Wetlands"},
{ str = "Fly to  Ironforge", typ = "fly"},
{ str = "Turn in #TURNINA Little Slime Goes a Long Way#", y = 23.38, x = 75.76, zone = "Ironforge", QT = 4512},
{ str = "Turn in #TURNINReturn to Tymor#", y = 4.82, x = 30.96, zone = "Ironforge", QT = 3461},
{ str = "Set your HS to Ironforge", y = 51.65, x = 18.53, zone = "Ironforge", typ = "home"},
{ str = "Accept #ACCEPTThe Smoldering Ruins of Thaurissan# pt.1", y = 55.3, x = 38.36, QA = 3702, zone = "Ironforge"},
{ str = "#DOQUEST*#Listen to her story", QC = 3702},
{ str = "Turn in #TURNINThe Smoldering Ruins of Thaurissan# pt.1 \nAccept #ACCEPTThe Smoldering Ruins of Thaurissan# pt.2", y = 55.3, x = 38.36, QA = 3701, zone = "Ironforge", QT = 3702},
{ str = "Fly to  Bunring Steppes", typ = "fly"},
{ str = "Accept #ACCEPTExtinguish the Firegut# ", y = 68.67, x = 84.55, QA = 3823, zone = "Burning Steppes"},
{ str = "Accept #ACCEPTFIFTY! YEP!#", y = 68.67, x = 84.55, QA = 4283, zone = "Burning Steppes"},
{ str = "Accept #ACCEPTDragonkin Menace#", y = 68.94, x = 85.82, QA = 4182, zone = "Burning Steppes"},
{ str = "#DOQUEST*#Start by killing Firegut Ogres", y = 46.78, x = 77.54, zone = "Burning Steppes", QC = { [3823] = 2}},
{ str = "Finish off #DOQUESTExtinguish the Firegut#", y = 37.39, x = 82.8, zone = "Burning Steppes", QC = 3823},
{ str = "Turn in #TURNINExtinguish the Firegut# ", y = 68.67, x = 84.55, zone = "Burning Steppes", QT = 3823},
{ str = "Accept #ACCEPTGor'tesh the Brute Lord#", y = 68.67, x = 84.55, QA = 3824, zone = "Burning Steppes"},
{ str = "Accept #ACCEPTBroodling Essence#  \nAccept #ACCEPTTablet of the Seven#", y = 24, x = 65.23, QA = {4726,4296}, zone = "Burning Steppes"},
{ str = "#DOQUEST*#Kill broodlings as you go along, use the quest item when they get low\nDo #DOQUESTDragonkin Menace# \nPrioritize killing broodlings over anything else\n \nTurn in #ACCEPT*##TURNINA Taste of Flame#  \nSkip this step if you don't have the Black Dragonflight Molt", y = 31.56, x = 95.09, QA = 4022, zone = "Burning Steppes", QT = 4022},
{ str = "#DOQUEST*#Right click on the small stone obelisks on the ground\n \n#DOQUEST*#Transcribe the tablet", y = 40.71, x = 54.06, zone = "Burning Steppes", QC = 4296},
{ str = "Finish off #DOQUESTThe Smoldering Ruins of Thaurissan#", y = 36.67, x = 62.54, zone = "Burning Steppes", QC = 3701},
{ str = "#DOQUEST*#Kill orcs\n \nDo #DOQUESTGor'tesh the Brute Lord#", y = 54.72, x = 38.89, zone = "Burning Steppes", QC = 3824},
{ str = "Finish off #DOQUESTFIFTY! YEP!#", y = 34.71, x = 41.25, zone = "Burning Steppes", QC = 4283},
{ str = "Finish off #DOQUESTDragonkin Menace# and #DOQUESTBroodling Essence#", y = 36.81, x = 89.34, zone = "Burning Steppes", QC = { [4182] = 0, [4726] = 0}},
{ str = "Turn in #TURNINDragonkin Menace#  \nAccept #ACCEPTThe True Masters#", y = 68.94, x = 85.82, QA = 4183, zone = "Burning Steppes", QT = 4182},
{ str = "Turn in #TURNINFIFTY! YEP!#  \nTurn in #TURNINGor'tesh the Brute Lord#  \nAccept #ACCEPTOgre Head On A Stick = Party#", y = 68.67, x = 84.55, QA = 3825, zone = "Burning Steppes", QT = {4283,3824}},
{ str = "Fly to  Redridge Mountains", typ = "fly"},
{ str = "Turn in #TURNINThe True Masters#  \nAccept #ACCEPTThe True Masters#", y = 44.45, x = 29.98, QA = 4184, zone = "Redridge Mountains", QT = 4183},
{ str = "Fly to  Stormwind", typ = "fly"},
{ str = "Turn in #TURNINBetter Late Than Never#  \nAccept #ACCEPTGood Natured Emma#", y = 30.54, x = 48.46, QA = 5048, zone = "Stormwind City", QT = 5022},
{ str = "Find Ol'Emma, she can roam around SW from time to time \nTurn in #TURNINGood Natured Emma#  \nAccept #ACCEPTGood Luck Charm#", y = 41.95, x = 52.47, QA = 5050, zone = "Stormwind City", QT = 5048, unitscan = "Ol' Emma"},
{ str = "Accept #ACCEPTThe First and the Last#  \nTurn in #TURNINThe True Masters#  \nAccept #ACCEPTThe True Masters#", y = 17.97, x = 78.22, QA = {6182,4185}, zone = "Stormwind City", QT = 4184},
{ str = "#DOQUEST*#Speak with Lady Katrana Prestor and go through her whole dialogue\n \nTurn in #TURNINThe True Masters#", y = 17.97, x = 78.22, zone = "Stormwind City", QT = 4185},
{ str = "Accept #ACCEPTThe True Masters#", y = 17.97, x = 78.22, QA = 4186, zone = "Stormwind City"},
{ str = "Turn in #TURNINThe First and the Last#  \nAccept #ACCEPTHonor the Dead#  \nTurn in #TURNINHonor the Dead#  \nAccept #ACCEPTFlint Shadowmore#", y = 59.84, x = 75.77, QA = {6183,6184}, zone = "Stormwind City", QT = {6182,6183}},
{ str = "Fly to  Redridge Mountains", typ = "fly"},
{ str = "Turn in #TURNINThe True Masters#  \nAccept #ACCEPTThe True Masters#", y = 44.45, x = 29.98, QA = 4223, zone = "Redridge Mountains", QT = 4186},
{ str = "Fly to  Burning Steppes", typ = "fly"},
{ str = "Turn in #TURNINThe True Masters#  \nAccept #ACCEPTThe True Masters#", y = 69.01, x = 84.74, QA = 4224, zone = "Burning Steppes", QT = 4223},
{ str = "Turn in #TURNINBroodling Essence#  \nAccept #ACCEPTFelnok Steelspring#  \nTurn in #TURNINTablet of the Seven#", y = 24, x = 65.23, QA = 4808, zone = "Burning Steppes", QT = {4726,4296}},
{ str = "#DOQUEST*#Talk to Ragged John", QC = 4224},
{ str = "#DOQUEST*#Click on the dirt mound on top of the mountain", y = 46.7, x = 81.03, zone = "Burning Steppes", QC = 3825},
{ str = "Turn in #TURNINOgre Head On A Stick = Party#", y = 68.67, x = 84.55, zone = "Burning Steppes", QT = 3825},
{ str = "Turn in #TURNINThe True Masters#", y = 69.01, x = 84.74, zone = "Burning Steppes", QT = 4224},
{ str = "Hearth to Ironforge\nMake sure you have 2 stacks of noggenfogger with you\nWithdraw the follwing items: \nEverlook report \nStudies in spirit speaking \n4 relic fragments and Jaron's pick \n \nDeposit Tinkee's Letter in your bank "},
{ str = "Do the Gnomeregan cloth turn ins: \n#ACCEPT*##TURNIN*#Wool  \n#ACCEPT*##TURNIN*#Silk  \n#ACCEPT*##TURNIN*#Mageweave   \n#ACCEPT*##TURNIN*#Runecloth\nDo the Ironforge cloth turn ins: \n#ACCEPT*##TURNIN*#Wool  \n#ACCEPT*##TURNIN*#Silk  \n#ACCEPT*##TURNIN*#Mageweave  \n#ACCEPT*##TURNIN*#Runecloth\n \nTurn in #TURNINThe Smoldering Ruins of Thaurissan#", y = 55.3, x = 38.36, zone = "Ironforge", QT = 3701},
{ str = "Fly to  Southshore", typ = "fly"},
		}
	},

-----------47-48 Tanaris
	--[410] = {
	[4748] = {
		title = "57-58 WPL/EPL part 1",
		--n = "47-48 Tanaris",
		--pID = 409, nID = 411,
		--itemCount = 42,
		items = {


{ str = "Before starting this segment make sure you have 2 stacks of Noggenfogger Elixir or some other form of slow fall \n \nFly to Southshore\n \nSet your HS to Southshore", typ = "home"},
{ str = "Fly to  Western Plaguelands", typ = "fly"},
{ str = "Accept #ACCEPTTarget: Dalson's Tears#", y = 84.5, x = 42.97, QA = 5219, zone = "Western Plaguelands"},
{ str = "Accept #ACCEPTA Plague Upon Thee#", y = 84.83, x = 43.41, QA = 5903, zone = "Western Plaguelands"},
{ str = "Turn in #TURNINFlint Shadowmore#  \nAccept #ACCEPTThe Eastern Plagues#", y = 84.5, x = 43.6, QA = 6185, zone = "Western Plaguelands", QT = 6184},
{ str = "Accept #ACCEPTAll Along the Watchtowers#", y = 84.03, x = 42.7, QA = 5097, zone = "Western Plaguelands"},
{ str = "Turn in #TURNINThe Everlook Report#", y = 95.13, x = 98.79, zone = "Tirisfal Glades", QT = 6028},
{ str = "#DOQUEST*#Mark the fourth tower", y = 71.19, x = 46.61, zone = "Western Plaguelands", QC = { [5097] = 8}},
{ str = "Accept #ACCEPTThe Wildlife Suffers Too#", y = 64.66, x = 53.73, QA = 4984, zone = "Western Plaguelands"},
{ str = "#DOQUEST*#Kill wolves as you quest \nMake sure to kill Carrion Lurkers if you can't find any wolves since they share spawn points\n \nClick on Mrs. Dalson's Diary \nTurn in #ACCEPT*##TURNINMrs. Dalson's Diary#", y = 50.67, x = 47.8, QA = 5058, zone = "Western Plaguelands", QT = 5058},
{ str = "Look for the Wandering Skeleton as you quest around Dalson's Tears \nLoot the Dalson Outhouse Key\n \nTurn in #TURNINTarget: Dalson's Tears#  \nAccept #ACCEPTReturn to Chillwind Camp#", y = 51.9, x = 46.17, QA = 5220, zone = "Western Plaguelands", QT = 5219, unitscan = "WANDERING SKELETON"},
{ str = "Use the Outhouse Key to open the outhouse and summon Farmer Dalson \nTurn in #ACCEPT*##TURNINLocked Away#\n \nKill Farmer Dalson and loot Dalson Cabinet Key", y = 49.69, x = 48.15, zone = "Western Plaguelands"},
{ str = "Click on the cabinet upstairs \nTurn in #ACCEPT*##TURNINLocked Away#", y = 49.66, x = 47.36, QA = 5060, zone = "Western Plaguelands", QT = 5060},
{ str = "Turn in #TURNINGood Luck Charm#  \nAccept #ACCEPTTwo Halves Become One#", y = 54.05, x = 38.4, QA = 5051, zone = "Western Plaguelands", QT = 5050},
{ str = "#DOQUEST*#Look for the Jabbering Ghoul around the farm \nRight click the Other-Half-Charm to create a Good Luck Charm", QC = 5051, unitscan = "JABBERING GHOUL"},
{ str = "Turn in #TURNINTwo Halves Become One#", y = 54.05, x = 38.4, zone = "Western Plaguelands", QT = 5051},
{ str = "Finish off #DOQUESTThe Wildlife Suffers Too#", y = 46.65, x = 45.98, zone = "Western Plaguelands", QC = 4984},
{ str = "#DOQUEST*#Mark the third tower", y = 63.21, x = 44.21, zone = "Western Plaguelands", QC = { [5097] = 4}},
{ str = "#DOQUEST*#Mark the second tower", y = 66.17, x = 42.35, zone = "Western Plaguelands", QC = { [5097] = 2}},
{ str = "#DOQUEST*#Mark the first tower", y = 71.62, x = 40.07, zone = "Western Plaguelands", QC = { [5097] = 1}},
{ str = "Turn in #TURNINAll Along the Watchtowers#  \nAccept #ACCEPTScholomance#", y = 84.03, x = 42.7, QA = 5533, zone = "Western Plaguelands", QT = 5097},
{ str = "Throw away the Beacon Torch\n \nTurn in #TURNINScholomance#  \nAccept #ACCEPTSkeletal Fragments#", y = 83.77, x = 42.66, QA = 5537, zone = "Western Plaguelands", QT = 5533},
{ str = "Turn in #TURNINReturn to Chillwind Camp#  \nAccept #ACCEPTTarget: Writhing Haunt#", y = 84.5, x = 42.97, QA = 5222, zone = "Western Plaguelands", QT = 5220},
{ str = "#DOQUEST*#Stop by Andorhal and kill skeletons for fragments\n \nTurn in #TURNINTarget: Writhing Haunt#  \nAccept #ACCEPTReturn to Chillwind Camp#", y = 65.61, x = 53.01, QA = 5223, zone = "Western Plaguelands", QT = 5222},
{ str = "Turn in #TURNINThe Wildlife Suffers Too# pt.1 \nAccept #ACCEPTThe Wildlife Suffers Too# pt.2", y = 64.66, x = 53.73, QA = 4985, zone = "Western Plaguelands", QT = 4984},
{ str = "Do #DOQUESTThe Wildlife Suffers Too#", y = 47.39, x = 66.07, zone = "Western Plaguelands", QC = 4985},
{ str = "Turn in #TURNINThe Wildlife Suffers Too#  \nAccept #ACCEPTGlyphed Oaken Branch#", y = 64.66, x = 53.73, QA = 4986, zone = "Western Plaguelands", QT = 4985},
{ str = "Accept #ACCEPTDemon Dogs#  \nAccept #ACCEPTBlood Tinged Skies#  \nAccept #ACCEPTCarrion Grubbage#", y = 43.69, x = 7.56, QA = {5542,5543,5544}, zone = "Eastern Plaguelands"},
{ str = "#DOQUEST*#Kill worms as you go along\n#DOQUEST*#Kill Plaguebats\n#DOQUEST*#Kill Plaguehound Runts\n \n#DOQUEST*#Click on the first skeleton on the ground", y = 79.85, x = 28.8, zone = "Eastern Plaguelands", QC = { [6185] = 1}},
{ str = "#DOQUEST*#Click on the second skeleton on the ground", y = 74.87, x = 28.8, zone = "Eastern Plaguelands", QC = { [6185] = 4}},
{ str = "#DOQUEST*#Click on the third skeleton on the ground", y = 74.98, x = 27.17, zone = "Eastern Plaguelands", QC = { [6185] = 2}},
{ str = "Turn in #TURNINSister Pamela#\n \nAccept #ACCEPTPamela's Doll#", y = 90.79, x = 36.45, QA = 5149, zone = "Eastern Plaguelands"},
{ str = "#DOQUEST*#Find the 3 doll parts around Darrowshire", QC = 5149},
{ str = "Turn in #TURNINPamela's Doll#  \nAccept #ACCEPTAuntie Marlene#  \nAccept #ACCEPTUncle Carlin#", y = 90.79, x = 36.45, QA = {5152,5241}, zone = "Eastern Plaguelands", QT = 5149},
{ str = "#DOQUEST*##DOQUEST*#Finish off Plaguebats/Plaguehound Runts", y = 72.62, x = 34.85, zone = "Eastern Plaguelands", QC = { [5543] = 0, [5542] = 1}},
{ str = "#DOQUEST*#Kill Plaguehounds", y = 56.56, x = 54.48, zone = "Eastern Plaguelands", QC = { [5542] = 2}},
{ str = "Accept #ACCEPTThe Restless Souls#  \nAccept #ACCEPTZaeldarr the Outcast#", y = 63.85, x = 79.54, QA = {5281,6021}, zone = "Eastern Plaguelands"},
{ str = "Turn in #TURNINDuke Nicholas Zverenhoff#", y = 59.82, x = 81.43, zone = "Eastern Plaguelands", QT = 6030},
{ str = "Turn in #TURNINUncle Carlin#  \nAccept #ACCEPTDefenders of Darrowshire#", y = 59.76, x = 81.51, QA = 5211, zone = "Eastern Plaguelands", QT = 5241},
{ str = "Get the  Eastern Plaguelands FP", y = 59.27, x = 81.63, zone = "Eastern Plaguelands", typ = "fp"},
{ str = "#DOQUEST*#Kill all ghouls you encounter\n#DOQUEST*#Kill Frenzied Plaguehounds\n \nTurn in #TURNINTroubled Spirits of Kel'Theril#", y = 21.99, x = 53.5, zone = "Eastern Plaguelands", QT = 5245},
{ str = "#DOQUEST*#Look for termite mounds around Plaguewood", y = 23.65, x = 21.87, zone = "Eastern Plaguelands", QC = 5903},
{ str = "Turn in #TURNINThe Restless Souls#", y = 33.74, x = 14.44, zone = "Eastern Plaguelands", QT = 5281},
{ str = "Accept #ACCEPTAugustus' Receipt Book#", y = 33.48, x = 14.44, QA = 6164, zone = "Eastern Plaguelands"},
{ str = "#DOQUEST*#Go upstairs and loot the book on the ground", y = 31.12, x = 17.43, zone = "Eastern Plaguelands", QC = 6164},
{ str = "Turn in #TURNINAugustus' Receipt Book#", y = 33.48, x = 14.44, zone = "Eastern Plaguelands", QT = 6164},
{ str = "Finish off the following: \n#DOQUESTDefenders of Darrowshire# \n#DOQUESTCarrion Grubbage# \n#DOQUESTDemon Dogs#", y = 61.02, x = 67.83, zone = "Eastern Plaguelands", QC = { [5542] = 4, [5544] = 0, [5211] = 0}},
{ str = "Head to the mountain shortcut", y = 43.2, x = 29.75, zone = "Eastern Plaguelands"},
{ str = "Climb to the top of the hill", y = 41.6, x = 23.33, zone = "Eastern Plaguelands"},
{ str = "Use noggenfogger to slow fall to the other side", y = 40.33, x = 21.78, zone = "Eastern Plaguelands"},
{ str = "Turn in #TURNINDemon Dogs#  \nTurn in #TURNINBlood Tinged Skies#  \nTurn in #TURNINCarrion Grubbage#\nAccept #ACCEPTRedemption#\n#DOQUEST*#Sit down and listen to his story\n \nTurn in #TURNINRedemption#  \nAccept #ACCEPTOf Forgotten Memories#", y = 43.69, x = 7.56, QA = 5781, zone = "Eastern Plaguelands", QT = 5742},
{ str = "Enter the crypt and slay #DOQUESTZaeldarr the Outcast#", y = 84.86, x = 27.46, zone = "Eastern Plaguelands", QC = 6021},
{ str = "Click on the scroll on the ground \nAccept #ACCEPTHameya's Plea#", y = 85.21, x = 27.27, QA = 6024, zone = "Eastern Plaguelands"},
{ str = "#DOQUEST*#Summon Mercutio and his goons by clicking on the dirt pile, kill him while kiting the adds", y = 86.87, x = 28.3, zone = "Eastern Plaguelands", QC = 5781},
{ str = "Turn in #TURNINOf Forgotten Memories#  \nAccept #ACCEPTOf Lost Honor#", y = 43.69, x = 7.56, QA = 5845, zone = "Eastern Plaguelands", QT = 5781},
{ str = "Use your Hearthstone\n \nFly to  Western Plaguelands", typ = "fly"},
		}
	},

-----------48-48 The Hinterlands
	--[411] = {
	[4848] = {
		title = "58-59 WPL/EPL part 2",
		--n = "48-48 The Hinterlands",
		--pID = 410, nID = 412,
		--itemCount = 8,
		items = {


{ str = "Turn in #TURNINReturn to Chillwind Camp#  \nAccept #ACCEPTTarget: Gahrron's Withering#", y = 84.5, x = 42.97, QA = 5225, zone = "Western Plaguelands", QT = 5223},
{ str = "Turn in #TURNINA Plague Upon Thee#  \nAccept #ACCEPTA Plague Upon Thee#", y = 84.83, x = 43.41, QA = 5904, zone = "Western Plaguelands", QT = 5903},
{ str = "Turn in #TURNINThe Eastern Plagues#  \nAccept #ACCEPTThe Blightcaller Cometh#", y = 84.5, x = 43.6, QA = 6186, zone = "Western Plaguelands", QT = 6185},
{ str = "#DOQUEST*#Kill skeletons as you go along\n \nTurn in #TURNINAuntie Marlene#  \nAccept #ACCEPTA Strange Historian#", y = 78.57, x = 49.16, QA = 5153, zone = "Western Plaguelands", QT = 5152},
{ str = "#DOQUEST*#Click on the gravestone", y = 76.78, x = 49.68, zone = "Western Plaguelands", QC = 5153},
{ str = "Accept #ACCEPTA Matter of Time#  \nTurn in #TURNINA Strange Historian#  \nAccept #ACCEPTThe Annals of Darrowshire#", y = 66.76, x = 39.45, QA = {4971,5154}, zone = "Western Plaguelands", QT = 5153},
{ str = "#DOQUEST*#Loot books inside the Andorhal town hall until you get the correct one \nThe correct book's pages has a lighter shade of grey and sometimes the correct book won't spawn \nIf you're unlucky, you have to keep looting bad tomes until the good one spawns", y = 69.25, x = 43.56, zone = "Western Plaguelands", QC = 5154},
{ str = "#DOQUEST*#Use the temporal displacer on the grain silos", y = 62.67, x = 46.32, zone = "Western Plaguelands", QC = 4971},
{ str = "Quest turn in order here is important \nTurn in #TURNINA Matter of Time#  \nAccept #ACCEPTCounting Out Time# ", y = 66.76, x = 39.45, QA = 4972, zone = "Western Plaguelands", QT = 4971},
{ str = "Turn in #TURNINThe Annals of Darrowshire#", y = 66.76, x = 39.45, zone = "Western Plaguelands", QT = 5154},
{ str = "#DOQUEST*#Go outside and look for steel lockboxes", y = 72.47, x = 43.45, zone = "Western Plaguelands", QC = 4972},
{ str = "Turn in #TURNINCounting Out Time#  \nAccept #ACCEPTBrother Carlin#", y = 66.76, x = 39.45, QA = 5210, zone = "Western Plaguelands", QT = 4972},
{ str = "Turn in #TURNINSkeletal Fragments#", y = 83.77, x = 42.66, zone = "Western Plaguelands", QT = 5537},
{ str = "Fly to  Eastern Plaguelands", typ = "fly"},
{ str = "Turn in #TURNINBrother Carlin#  \nAccept #ACCEPTHeroes of Darrowshire#  \nAccept #ACCEPTVillains of Darrowshire#", y = 59.76, x = 81.51, QA = {5168,5181}, zone = "Eastern Plaguelands", QT = 5210},
{ str = "Turn in #TURNINZaeldarr the Outcast#", y = 63.85, x = 79.54, zone = "Eastern Plaguelands", QT = 6021},
{ str = "Do #DOQUESTOf Lost Honor#", y = 33.95, x = 71.29, zone = "Eastern Plaguelands", QC = 5845},
{ str = "#DOQUEST*#Kill Infiltrator Hameya, he patrols around the troll temple", y = 16.52, x = 70.69, zone = "Eastern Plaguelands", QC = 6024},
{ str = "#DOQUEST*#Loot Horgus' Skull underwater", y = 49.93, x = 51.11, zone = "Eastern Plaguelands", QC = { [5181] = 1}},
{ str = "Finish off #DOQUESTVillains of Darrowshire#", y = 65.76, x = 53.9, zone = "Eastern Plaguelands", QC = 5181},
{ str = "Click on the mound of dirt next to the wooden cart \nTurn in #TURNINHameya's Plea#", y = 86.15, x = 28.03, zone = "Eastern Plaguelands", QT = 6024},
{ str = "Turn in #TURNINOf Lost Honor#  \nAccept #ACCEPTOf Love and Family#", y = 43.69, x = 7.56, QA = 5846, zone = "Eastern Plaguelands", QT = 5845},
{ str = "Head to Western Plaguelands \n#DOQUEST*#Loot the shield on the ground", y = 57.19, x = 63.79, zone = "Western Plaguelands", QC = { [5168] = 2}},
{ str = "#DOQUEST*#Kill the cauldron lord\n \nTurn in #TURNINTarget: Gahrron's Withering#  \nAccept #ACCEPTReturn to Chillwind Camp#", y = 58.47, x = 62.54, QA = 5226, zone = "Western Plaguelands", QT = 5225},
{ str = "Turn in #TURNINThe Wildlife Suffers Too#  \nAccept #ACCEPTGlyphed Oaken Branch#", y = 64.66, x = 53.73, QA = 4986, zone = "Western Plaguelands", QT = 4985},
{ str = "Click on the crate at the middle of the lumber mill and place the termite barrel \nClick on the termite barrel, turn in #TURNINA Plague Upon Thee#  \nAccept #ACCEPTA Plague Upon Thee#", y = 31.91, x = 48.38, QA = 6389, zone = "Western Plaguelands", QT = 5904},
{ str = "Accept #ACCEPTUnfinished Business#", y = 28.05, x = 51.92, QA = 6004, zone = "Western Plaguelands"},
{ str = "Do #DOQUESTUnfinished Business#", y = 42.7, x = 51.22, zone = "Western Plaguelands", QC = 6004},
{ str = "Turn in #TURNINUnfinished Business#  \nAccept #ACCEPTUnfinished Business#", y = 28.05, x = 51.92, QA = 6023, zone = "Western Plaguelands", QT = 6004},
{ str = "#DOQUEST*#Kill Cavalier Durgen, he spawns at the top of the tower and patrols all the way down \nDo your best to avoid the level 63 elite mob on top of the tower, keep grinding mobs until you have an opening.", y = 23.39, x = 54.94, zone = "Western Plaguelands", QC = { [6023] = 2}},
{ str = "#DOQUEST*#Kill Huntsman Radley", y = 36.11, x = 57.81, zone = "Western Plaguelands", QC = { [6023] = 1}},
{ str = "Turn in #TURNINUnfinished Business#  \nAccept #ACCEPTUnfinished Business#", y = 28.05, x = 51.92, QA = 6025, zone = "Western Plaguelands", QT = 6023},
{ str = "#DOQUEST*#Head to Hearthglen \nClimb to the top of the tower", y = 18.57, x = 45.78, zone = "Western Plaguelands", QC = 6025},
{ str = "#DOQUEST*#Loot Davil's Libram inside the town hall, use your pet to pull mobs away \nPay attention to the rare mob that patrols the building.", y = 18.98, x = 42.53, zone = "Western Plaguelands", QC = { [5168] = 1}},
{ str = "Turn in #TURNINUnfinished Business#", y = 28.05, x = 51.92, zone = "Western Plaguelands", QT = 6025},
{ str = "Grind mobs around the Lumber mill until your HS is off cooldown \nUse your Hearthstone\n \nFly to  Eastern Plaguelands", typ = "fly"},
{ str = "Turn in #TURNINHeroes of Darrowshire#  \nTurn in #TURNINVillains of Darrowshire#  \nAccept #ACCEPTMarauders of Darrowshire#", y = 59.76, x = 81.51, QA = 5206, zone = "Eastern Plaguelands", QT = {5168,5181}},
{ str = "#DOQUEST*#Kill Scourge Champions, loot Fetid Skulls and use the Mystic Crystal \nScourge Champions share spawns with several different mobs, make sure to keep grinding mobs if you can't find any", y = 42.02, x = 83.27, zone = "Eastern Plaguelands", QC = 5206},
{ str = "Turn in #TURNINDefenders of Darrowshire#  \nTurn in #TURNINMarauders of Darrowshire#  \nAccept #ACCEPTReturn to Chromie#", y = 59.76, x = 81.51, QA = 5941, zone = "Eastern Plaguelands", QT = {5211,5206}},
{ str = "Fly to  Western Plaguelands", typ = "fly"},
{ str = "Turn in #TURNINReturn to Chillwind Camp#", y = 84.5, x = 42.97, zone = "Western Plaguelands", QT = 5226},
{ str = "Turn in #ACCEPT*##TURNINMission Accomplished!#", QA = 5237, QT = 5237},
{ str = "Make sure to turn in all your scourgestones before continuing to the next step"},
{ str = "Turn in #TURNINA Plague Upon Thee#", y = 84.83, x = 43.41, zone = "Western Plaguelands", QT = 6389},
{ str = "Turn in #TURNINReturn to Chromie#", y = 66.76, x = 39.45, zone = "Western Plaguelands", QT = 5941},
{ str = "Turn in #TURNINOf Love and Family#", y = 75.36, x = 65.77, zone = "Western Plaguelands", QT = 5846},
{ str = "Use the website unstuck tool to teleport to SW \nOR \nThrow away your HS and unstuck back to Chillwind Camp, then fly to  Ironforge", typ = "fly"},
		}
	},

-----------48-49 Stranglethorn Vale
	--[412] = {
	[4849] = {
		title = "59-59 Winterspring/Silithus",
		--n = "48-49 Stranglethorn Vale",
		--pID = 411, nID = 413,
		--itemCount = 27,
		items = {

{ str = "Take the tram to SW\n \nTurn in #TURNINThe Blightcaller Cometh#", y = 17.97, x = 78.22, zone = "Stormwind City", QT = 6186},
{ str = "Do the Stormwind cloth turn ins: \n#ACCEPT*##TURNIN*#Wool  \n#ACCEPT*##TURNIN*#Silk  \n#ACCEPT*##TURNIN*#Mageweave  \n#ACCEPT*##TURNIN*#Runecloth", y = 73.99, x = 44.27, QA = {7795,7793,7791,7794}, zone = "Stormwind City", QT = {7795,7793,7791,7794}},
{ str = "Fly to  Booty Bay", typ = "fly"},
{ str = "Withdraw Tinkee's Letter from your bank \n \nTake the boat to ratchet"},
{ str = "Fly to  Winterspring", typ = "fly"},
{ str = "Once you get to level 59, stable your current pet, head to northern winterspring and replace it by a level 59 Owl\n \nSet your HS to Everlook", typ = "home"},
{ str = "Turn in #TURNINFelnok Steelspring#  \nAccept #ACCEPTChillwind Horns#", y = 38.61, x = 61.62, QA = 4809, zone = "Winterspring", QT = 4808},
{ str = "Accept #ACCEPTLuck Be With You#", y = 38.29, x = 61.91, QA = 969, zone = "Winterspring"},
{ str = "Accept #ACCEPTAre We There, Yeti?#", y = 37.61, x = 60.88, QA = 3783, zone = "Winterspring"},
{ str = "Do #DOQUESTAre We There, Yeti?#", y = 39.27, x = 70.85, zone = "Winterspring", QC = 3783},
{ str = "Turn in #TURNINAre We There, Yeti?#", y = 37.61, x = 60.88, zone = "Winterspring", QT = 3783},
{ str = "Accept #ACCEPTAre We There, Yeti?#", y = 37.61, x = 60.88, QA = 977, zone = "Winterspring"},
{ str = "#DOQUEST*#Kill chillwind chimeras, don't go out of your way to finish it\n \nDo #DOQUESTHigh Chief Winterfall#", y = 38.3, x = 69.56, zone = "Winterspring", QC = 5121},
{ str = "Loot the Crudely-written Log from the High Chief \nAccept #ACCEPTThe Final Piece#", y = 38.3, x = 69.56, QA = 5123, zone = "Winterspring"},
{ str = "Do #DOQUESTAre We There, Yeti?#", y = 40.03, x = 70.3, zone = "Winterspring", QC = 977},
{ str = "Start the escort quest \nAccept #ACCEPTGuardians of the Altar#", y = 59.47, x = 63.07, QA = 4901, zone = "Winterspring"},
{ str = "#DOQUEST*#Escort Ranshalla and click on the torches once she enters one of the caves", QC = 4901},
{ str = "Head south to Frowstwhisper Gorge \nDo #DOQUESTLuck Be With You#  \nThe elite giants are immune to frost, not every class can solo this quest", y = 68.33, x = 59.06, zone = "Winterspring", QC = 969},
{ str = "Hearth to Everlook - Do not skip this step\n \nTurn in #TURNINAre We There, Yeti?#  \nAccept #ACCEPTAre We There, Yeti?#", y = 37.61, x = 60.88, QA = 5163, zone = "Winterspring", QT = 977},
{ str = "#DOQUEST*#Use the Mechanical Yet on Legacki", y = 38.61, x = 61.54, zone = "Winterspring", QC = { [5163] = 1}},
{ str = "Turn in #TURNINLuck Be With You#", y = 38.29, x = 61.91, zone = "Winterspring", QT = 969},
{ str = "Withdraw the following:  \nRabine's Letter \nSilvery Claws \nIrontree Heart \nRemains of Trey Lightforge \nShadow Lord Fel'dan's Head"},
{ str = "Turn in #TURNINHigh Chief Winterfall#  \nTurn in #TURNINThe Final Piece#  \nAccept #ACCEPTWords of the High Chief#", y = 45.16, x = 31.26, QA = 5128, zone = "Winterspring", QT = {5121,5123}},
{ str = "Head to Moonglade\n \nTurn in #TURNINRabine Saturna#  \nAccept #ACCEPTWasteland#", y = 45.09, x = 51.68, QA = 1124, zone = "Moonglade", QT = 6762},
{ str = "Finish the dialogue with Rabine \nAccept #ACCEPTA Reliquary of Purity#  \nSkip this step if the Dire Maul dialogue is not available", y = 45.09, x = 51.68, QA = 5527, zone = "Moonglade"},
{ str = "Unstuck to the Moonglade graveyard and spirit rez\n \nGet the  Moonglade FP", y = 67.34, x = 48.13, zone = "Moonglade", typ = "fp"},
{ str = "Head back to the fulborg tunnel \nOnce the zone text changes to Felwood, unstuck back to the graveyard and spirit rez\n \nRun south to the slime pond \nDeath warp to southern Felwood", y = 66.77, x = 40.84, zone = "Felwood"},
{ str = "Turn in #TURNINA Final Blow#", y = 82.1, x = 51.21, zone = "Felwood", QT = 5242},
{ str = "Turn in #TURNINThe Remains of Trey Lightforge#", y = 82.01, x = 51.34, zone = "Felwood", QT = 5385},
{ str = "Turn in #TURNINWords of the High Chief#", y = 81.75, x = 51.13, zone = "Felwood", QT = 5128},
{ str = "Turn in #TURNINSilver Heart#  \nAccept #ACCEPTAquementas#", y = 81.5, x = 51.34, QA = 4005, zone = "Felwood", QT = 4084},
{ str = "Run south to Ashenvale unstuck and spirit rez at Astranaar\n \nFly to  Tanaris", typ = "fly"},
{ str = "Accept #ACCEPTPawn Captures Queen#", y = 26.96, x = 50.88, QA = 4507, zone = "Tanaris"},
{ str = "#DOQUEST*#Use the Mechanical Yeti on Sprinkle", y = 26.87, x = 51.05, zone = "Tanaris", QC = { [5163] = 2}},
{ str = "Head to the pirate area \nRight click on Eridan's Supplies \nUse the book of Aquor to summon #DOQUESTAquementas#", y = 49.93, x = 70.43, zone = "Tanaris", QC = 4005},
{ str = "Head back to Gadgetzan \nFly to  Un'Goro Crater", typ = "fly"},
{ str = "Turn in #TURNINAquementas#  \nAccept #ACCEPTLinken's Adventure#", y = 2.69, x = 41.91, QA = 3961, zone = "Un'Goro Crater", QT = 4005},
{ str = "Turn in #TURNINLinken's Adventure#  \nAccept #ACCEPTIt's Dangerous to Go Alone#", y = 8.09, x = 44.65, QA = 3962, zone = "Un'Goro Crater", QT = 3961},
{ str = "#DOQUEST*#Use the Mechanical Yeti on Quixxil", y = 9.37, x = 43.67, zone = "Un'Goro Crater", QC = { [5163] = 4}},
{ str = "#DOQUEST*#Equip the Silver Totem of Aquementas on your off-hand \nDeafeat Blazerunner at the top of the volcano\n \n#DOQUEST*#Click on the chest at the back of the cave", y = 49.98, x = 50.28, zone = "Un'Goro Crater", QC = { [3962] = 2}},
{ str = "Head south and enter the bug hole \nUse the Gorishi Queen Lure after clearing the circular room \n#DOQUEST*#Clear all 3 waves of mobs", y = 81.4, x = 44.13, zone = "Un'Goro Crater", QC = 4507},
{ str = "Head to Silithus", y = 22.08, x = 29.05, zone = "Un'Goro Crater"},
{ str = "Turn in #TURNINWasteland#  \nAccept #ACCEPTThe Spirits of Southwind#", y = 18.93, x = 81.87, QA = 1125, zone = "Silithus", QT = 1124},
{ str = "Head to Cenarion Hold\n \nTalk to the goblin at the 2nd floor of the inn \nAccept #ACCEPTDeadly Desert Venom#", y = 38.6, x = 51.8, QA = 8277, zone = "Silithus"},
{ str = "Click on the wanted poster \nAccept #ACCEPTWanted - Deathclasp, Terror of the Sands#", y = 38.2, x = 51.3, QA = 8283, zone = "Silithus"},
{ str = "Turn in #TURNINTaking Back Silithus#\n \nAccept #ACCEPTSecuring the Supply Lines#", y = 38.2, x = 51.2, QA = 8280, zone = "Silithus"},
{ str = "Accept #ACCEPTThe Twilight Mystery#", y = 37.29, x = 49.6, QA = 8284, zone = "Silithus"},
{ str = "Accept #ACCEPTDearest Natalia#", y = 34.19, x = 49.2, QA = 8304, zone = "Silithus"},
{ str = "Accept #ACCEPTSecret Communication#", y = 37.79, x = 48.6, QA = 8318, zone = "Silithus"},
{ str = "Kill #DOQUEST*#Dredge Striker (x15)\nCollect #DOQUEST*#Stonelash Scorpid Stinger (x8) \nCollect #DOQUEST*#Sand Skitterer Fang (x8)\n \n#DOQUEST*#Click on the small urn inside the lodge", y = 55.35, x = 63.22, zone = "Silithus", QC = 5527},
{ str = "Finish off #DOQUESTThe Spirits of Southwind#", y = 49.9, x = 63.53, zone = "Silithus", QC = 1125},
{ str = "Turn in #TURNINThe Spirits of Southwind#  \nAccept #ACCEPTHive in the Tower#", y = 18.93, x = 81.87, QA = 1126, zone = "Silithus", QT = 1125},
{ str = "#DOQUEST*#Clear the 3 bugs that spawn at the base of the tower \nClick on the object at the top of the tower \nKill the 2 ambushers that spawn after clicking it", y = 52.55, x = 60.22, zone = "Silithus", QC = 1126},
{ str = "Turn in #TURNINHive in the Tower#  \nAccept #ACCEPTUmber, Archivist#", y = 18.93, x = 81.87, QA = 6844, zone = "Silithus", QT = 1126},
{ str = "From this point forward, stop questing in silithus and skip straight to the part 2 of this guide once you have enough XP to ding from turn ins \nYou need about 55k xp total, assuming you haven't skipped any quests\n \nCollect #DOQUEST*#Twilight Tablet Fragment (x8)", y = 13.69, x = 23.5, zone = "Silithus", QC = { [8284] = 1}},
{ str = "Finish off the following quests: \n#DOQUESTDeadly Desert Venom#  \n#DOQUESTSecuring the Supply Lines#", y = 41.98, x = 67.68, zone = "Silithus", QC = { [8277] = 0, [8280] = 0}},
{ str = "Turn in #TURNINThe Twilight Mystery# \nAccept #ACCEPTThe Deserter#", y = 37.29, x = 49.7, QA = 8285, zone = "Silithus", QT = 8284},
{ str = "Turn in #TURNINSecuring the Supply Lines# \nAccept #ACCEPTStepping Up Security#", y = 38.2, x = 51.1, QA = 8281, zone = "Silithus", QT = 8280},
{ str = "Turn in #TURNINDeadly Desert Venom# \nAccept #ACCEPTNoggle's Last Hope#", y = 38.5, x = 51.7, QA = 8278, zone = "Silithus", QT = 8277},
{ str = "Collect #DOQUEST*#Stonelash Flayer Stinger (x3) \nCollect #DOQUEST*#Stonelash Pincer Stinger (x3) \nCollect #DOQUEST*#Rock Stalker Fang (x3)\n \nKill #DOQUEST*#Dredge Crusher (x20)", y = 53.33, x = 39.31, zone = "Silithus", QC = { [8281] = 1}},
{ str = "#DOQUEST*#Speak with Rutgar", y = 88.5, x = 41.3, zone = "Silithus", QC = { [8304] = 2}},
{ str = "#DOQUEST*#Speak with Frankal", y = 88.79, x = 40.79, zone = "Silithus", QC = { [8304] = 1}},
{ str = "Collect #DOQUEST*#Deathclasp's Pincer", y = 92.2, x = 45, zone = "Silithus", QC = { [8283] = 1}},
{ str = "Finish off #DOQUESTNoggle's Last Hope#", y = 83.83, x = 39.44, zone = "Silithus", QC = 8278},
{ str = "Turn in #TURNINThe Deserter# \nAccept #ACCEPTThe Twilight Lexicon#", y = 69.69, x = 67.2, QA = 8279, zone = "Silithus", QT = 8285},
{ str = "Make sure to finish off all quests before heading back to Cenarion Hold \n  \nTurn in #TURNINStepping Up Security#", y = 38.2, x = 51.1, zone = "Silithus", QT = 8281},
{ str = "Turn in #TURNINNoggle's Last Hope# \nAccept #ACCEPTNoggle's Lost Satchel#", y = 38.5, x = 51.7, QA = 8282, zone = "Silithus", QT = 8278},
{ str = "Turn in #TURNINDearest Natalia#", y = 34.3, x = 49.2, zone = "Silithus", QT = 8304},
{ str = "Turn in #TURNINWanted - Deathclasp, Terror of the Sands#", y = 33.6, x = 50.8, zone = "Silithus", QT = 8283},
{ str = "Kill twilight cultists as you quest \nCollect #DOQUEST*#Encrypted Twilight Text (x10)\n \nKill #DOQUEST*#Twilight Keeper Havunth \nHe patrols the twilight camp next to Cenarion Hold", y = 42.22, x = 40.86, zone = "Silithus", QC = { [8279] = 4}, unitscan = "Twilight Keeper Havunth"},
{ str = "Kill #DOQUEST*#Twilight Keeper Mayna \nShe patrols the twilight camp directly west of Cenarion Hold", y = 36.62, x = 26.34, zone = "Silithus", QC = { [8279] = 1}, unitscan == "TWILIGHT KEEPER MAYNA"},
{ str = "Kill #DOQUEST*#Twilight Keeper Exeter \nHe is at the back of the southwestern twilight camp", y = 86.37, x = 16.08, zone = "Silithus", QC = { [8279] = 2}},
{ str = "#DOQUEST*#Finish off looting the 10 twilight texts", y = 44.5, x = 39.4, zone = "Silithus", QC = { [8318] = 1}},
{ str = "Collect #DOQUEST*#Noggle's Satchel", y = 91.39, x = 44.5, zone = "Silithus", QC = { [8282] = 1}},
{ str = "Turn in #TURNINThe Twilight Lexicon# \nAccept #ACCEPTA Terrible Purpose# \nAccept #ACCEPTTrue Believers#", y = 69.79, x = 67.2, QA = {8287,8323}, zone = "Silithus", QT = 8279},
{ str = "Grind mobs at the twilight camps until you get 10 Encrypted Twilight Texts \nTurn in #TURNINTrue Believers#", y = 69.75, x = 67.19, zone = "Silithus", QT = 8323},
{ str = "Head to Cenarion Hold \nTurn in #TURNINNoggle's Lost Satchel#", y = 38.5, x = 51.7, zone = "Silithus", QT = 8282},
{ str = "Turn in #TURNINA Terrible Purpose#", y = 34.19, x = 49.2, zone = "Silithus", QT = 8287},
{ str = "Finish off #DOQUESTSecret Communication#", y = 37.5, x = 48.7, zone = "Silithus", QC = 8318},
{ str = "Turn in #TURNINSecret Communication#", y = 37.7, x = 48.6, zone = "Silithus", QT = 8318},
{ str = "Fly to  Un'Goro Crater", typ = "fly"},
		}
	},
	
--------49-50 Blasted Lands
	--[413] = {
	[4950] = {
		title = "59-60 Final quest hand ins",
		--n = "49-50 Blasted Lands",
		--pID = 412, nID = 501,
		--itemCount = 30,
		items = {


{ str = "Fly to Un'Goro Crater\n \nTurn in #TURNINIt's Dangerous to Go Alone# (7300xp) ", y = 8.09, x = 44.65, zone = "Un'Goro Crater", QT = 3962},
{ str = "Fly to  Tanaris", typ = "fly"},
{ str = "Turn in #TURNINPawn Captures Queen# (5450xp)  \nAccept #ACCEPTCalm Before the Storm# ", y = 26.96, x = 50.88, QA = 4508, zone = "Tanaris", QT = 4507},
{ str = "Turn in #TURNINSuper Sticky# (5450xp)", y = 26.75, x = 51.56, zone = "Tanaris", QT = 4504},
{ str = "Hearth to Everlook\n \nTurn in #TURNINAre We There, Yeti?# (7750xp) ", y = 37.61, x = 60.88, zone = "Winterspring", QT = 5163},
{ str = "Finish off/Turn in #TURNINChillwind Horns# (5450xp)  \nSkip this quest if you have enough xp to ding from all the quest turn-ins from moonglade/darnassus \n(about 35k xp total)\nGrind until you are 34.5k xp away from 60\n \nFly to  Moonglade", typ = "fly"},
{ str = "Turn in #TURNINUmber, Archivist# (3000xp)  \nAccept #ACCEPTUncovering Past Secrets# ", y = 35.6, x = 44.88, QA = 6845, zone = "Moonglade", QT = 6844},
{ str = "Turn in #TURNINUncovering Past Secrets# (7550xp) ", y = 45.09, x = 51.68, zone = "Moonglade", QT = 6845},
{ str = "Turn in #TURNINA Reliquary of Purity# (6600xp) ", y = 45.09, x = 51.68, zone = "Moonglade", QT = 5527},
{ str = "Turn in #ACCEPT*##TURNINUnder the Chitin Was...# (3000xp) ", y = 35.62, x = 44.87, QA = 1185, zone = "Moonglade", QT = 1185},
{ str = "Fly to Felwood ang grind fulborgs if you don't have enough XP to ding 60 from quest turn ins in Darnassus\n \nAssuming you didn't skip any quests you should be 14.5k experience away from level 60"},
{ str = "Fly to  Teldrassil", typ = "fly"},
{ str = "Turn in #TURNINCalm Before the Storm# (540xp)  \nAccept #ACCEPTCalm Before the Storm# ", y = 85.63, x = 41.84, QA = 4510, zone = "Darnassus", QT = 4508},
{ str = "Turn in #TURNINCalm Before the Storm# (8150xp) ", y = 42.43, x = 39.38, zone = "Darnassus", QT = 4510},
{ str = "Turn in #TURNINGlyphed Oaken Branch# at the middle floor (5800xp) ", y = 8.4, x = 35.37, zone = "Darnassus", QT = 4986},

		}
	},
}